"""
lessons.py — Real per-lesson quiz content: genuine questions with correct
answers, difficulty, and Bloom's cognitive-level tags (not placeholder
stems like the old QUIZ_TEMPLATES in data.py).

Includes 6 Mathematics lessons whose ids (fractions-bodmas,
pythagorean-theorem, linear-equations, algebraic-fractions,
volume-capacity, number-patterns) are deliberately the same lesson_ids
tagged onto the real playable games in emotion-backend's game_catalog.py
(Fraction Room Rescue, Uncharted Waters, Equations Eco, Escape the Dark
Room, Fish Tank Shop, Pattern Islands respectively) - this is what lets
the Teacher Console's Game Recommendation Engine offer a game genuinely
related to the lesson the teacher picked, not just its subject.
"""

LESSONS = {
    "python-functions": {
        "title": "Python Functions",
        "subject": "Programming",
        "questions": [
            {
                "id": "pf-r1", "lo_level": "remember", "difficulty": "easy",
                "question": "Which keyword is used to define a function in Python?",
                "options": ["func", "def", "function", "lambda"],
                "answer": "def",
            },
            {
                "id": "pf-r2", "lo_level": "remember", "difficulty": "easy",
                "question": "What does a function return by default if it has no return statement?",
                "options": ["0", "None", "an empty string", "an error"],
                "answer": "None",
            },
            {
                "id": "pf-u1", "lo_level": "understand", "difficulty": "easy",
                "question": "What is the purpose of a default parameter value in a function?",
                "options": [
                    "It makes the parameter required",
                    "It provides a fallback value if the caller doesn't supply one",
                    "It converts the parameter to a string",
                    "It deletes the parameter after use",
                ],
                "answer": "It provides a fallback value if the caller doesn't supply one",
            },
            {
                "id": "pf-u2", "lo_level": "understand", "difficulty": "medium",
                "question": "Why can using a mutable default argument (like a list) be risky?",
                "options": [
                    "It's shared across all calls unless explicitly reset",
                    "Python forbids mutable defaults",
                    "It slows down the function significantly",
                    "It cannot hold more than one item",
                ],
                "answer": "It's shared across all calls unless explicitly reset",
            },
            {
                "id": "pf-a1", "lo_level": "apply", "difficulty": "medium",
                "question": "def add(a, b=10): return a + b. What does add(5) return?",
                "options": ["5", "10", "15", "TypeError"],
                "answer": "15",
            },
            {
                "id": "pf-a2", "lo_level": "apply", "difficulty": "hard",
                "question": "def f(*args, **kwargs): pass. How would you call f with 1, 2 as positional and x=3 as keyword?",
                "options": ["f(1, 2, x=3)", "f([1, 2], {'x': 3})", "f(1, 2, 3)", "f(x=3, 1, 2)"],
                "answer": "f(1, 2, x=3)",
            },
            {
                "id": "pf-n1", "lo_level": "analyze", "difficulty": "medium",
                "question": "Two functions both compute a factorial, one recursive and one iterative. For very large n, which is more likely to fail first?",
                "options": ["The iterative version", "The recursive version, due to recursion depth limits", "Neither will fail", "Both fail identically"],
                "answer": "The recursive version, due to recursion depth limits",
            },
            {
                "id": "pf-n2", "lo_level": "analyze", "difficulty": "hard",
                "question": "A function modifies a list passed as an argument, and the caller sees the change outside the function. Why?",
                "options": [
                    "Python passes lists by value",
                    "Lists are mutable and passed by object reference",
                    "The function creates a global variable",
                    "This should never happen in Python",
                ],
                "answer": "Lists are mutable and passed by object reference",
            },
            {
                "id": "pf-e1", "lo_level": "evaluate", "difficulty": "hard",
                "question": "A colleague argues all functions should use **kwargs instead of named parameters for flexibility. What's the strongest counter-argument?",
                "options": [
                    "**kwargs is slower to type",
                    "Named parameters give clearer signatures, better error messages, and IDE support",
                    "Python doesn't allow more than 3 named parameters",
                    "There is no valid counter-argument",
                ],
                "answer": "Named parameters give clearer signatures, better error messages, and IDE support",
            },
            {
                "id": "pf-c1", "lo_level": "create", "difficulty": "hard",
                "question": "You need a function that logs every call to another function without modifying that function's code. What pattern would you design?",
                "options": ["A decorator", "A global variable", "A second copy of the function", "A try/except block"],
                "answer": "A decorator",
            },
        ],
    },
    "photosynthesis": {
        "title": "Photosynthesis",
        "subject": "Science",
        "questions": [
            {
                "id": "ph-r1", "lo_level": "remember", "difficulty": "easy",
                "question": "What gas do plants absorb from the atmosphere during photosynthesis?",
                "options": ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"],
                "answer": "Carbon dioxide",
            },
            {
                "id": "ph-r2", "lo_level": "remember", "difficulty": "easy",
                "question": "In which cell organelle does photosynthesis take place?",
                "options": ["Mitochondria", "Nucleus", "Chloroplast", "Ribosome"],
                "answer": "Chloroplast",
            },
            {
                "id": "ph-u1", "lo_level": "understand", "difficulty": "easy",
                "question": "Why do plants appear green?",
                "options": [
                    "Chlorophyll absorbs green light",
                    "Chlorophyll reflects green light and absorbs other wavelengths",
                    "Green is the only color plants can produce",
                    "Plants filter out all colors except green",
                ],
                "answer": "Chlorophyll reflects green light and absorbs other wavelengths",
            },
            {
                "id": "ph-u2", "lo_level": "understand", "difficulty": "medium",
                "question": "What is the overall relationship between photosynthesis and cellular respiration?",
                "options": [
                    "They are unrelated processes",
                    "Photosynthesis produces the glucose and oxygen that respiration consumes",
                    "Respiration only happens in plants",
                    "Photosynthesis consumes glucose to make CO2",
                ],
                "answer": "Photosynthesis produces the glucose and oxygen that respiration consumes",
            },
            {
                "id": "ph-a1", "lo_level": "apply", "difficulty": "medium",
                "question": "A plant is moved from bright sunlight to a dim room. What would you predict happens to its rate of photosynthesis?",
                "options": ["It increases", "It decreases", "It stays exactly the same", "Photosynthesis stops needing light entirely"],
                "answer": "It decreases",
            },
            {
                "id": "ph-a2", "lo_level": "apply", "difficulty": "hard",
                "question": "If CO2 levels in a sealed greenhouse are experimentally doubled (with light/water non-limiting), what would you expect?",
                "options": [
                    "Photosynthesis rate increases, up to a saturation point",
                    "Photosynthesis stops entirely",
                    "The plant only performs respiration",
                    "No measurable change ever occurs",
                ],
                "answer": "Photosynthesis rate increases, up to a saturation point",
            },
            {
                "id": "ph-n1", "lo_level": "analyze", "difficulty": "medium",
                "question": "A plant grown in blue-red LED light grows normally, but one grown only in pure green light grows poorly. Why?",
                "options": [
                    "Green light is toxic to plants",
                    "Chlorophyll poorly absorbs green wavelengths, so less light energy is captured",
                    "Plants cannot see green light",
                    "Green light contains no photons",
                ],
                "answer": "Chlorophyll poorly absorbs green wavelengths, so less light energy is captured",
            },
            {
                "id": "ph-n2", "lo_level": "analyze", "difficulty": "hard",
                "question": "During a drought, a plant closes its stomata to conserve water. What is the direct consequence for photosynthesis?",
                "options": [
                    "No effect - stomata are unrelated to photosynthesis",
                    "Reduced CO2 intake limits the rate of photosynthesis",
                    "Photosynthesis rate increases",
                    "The plant switches entirely to respiration",
                ],
                "answer": "Reduced CO2 intake limits the rate of photosynthesis",
            },
            {
                "id": "ph-e1", "lo_level": "evaluate", "difficulty": "hard",
                "question": "A farmer claims adding more fertilizer will always increase crop photosynthesis rate. What's the strongest critique?",
                "options": [
                    "Fertilizer has zero effect on plants",
                    "Photosynthesis is also limited by light, CO2, and water - fertilizer alone can't overcome those limits",
                    "Fertilizer only works on animals",
                    "There is no valid critique",
                ],
                "answer": "Photosynthesis is also limited by light, CO2, and water - fertilizer alone can't overcome those limits",
            },
            {
                "id": "ph-c1", "lo_level": "create", "difficulty": "hard",
                "question": "Design a simple experiment to test whether light intensity affects the rate of photosynthesis in an aquatic plant.",
                "options": [
                    "Count bubbles released per minute at varying distances from a lamp",
                    "Measure the plant's height once, one time",
                    "Ask the plant to self-report",
                    "Weigh the pot before planting",
                ],
                "answer": "Count bubbles released per minute at varying distances from a lamp",
            },
        ],
    },
    "fractions-bodmas": {
        "title": "Fractions & BODMAS",
        "subject": "Mathematics",
        "questions": [
            # ---- Set 1 ----
            {"id": "fr-r1", "lo_level": "remember", "difficulty": "easy", "set": 1,
             "question": "What does the \"B\" in BODMAS stand for?",
             "answer": "Brackets"},
            {"id": "fr-r2", "lo_level": "remember", "difficulty": "easy", "set": 1,
             "question": "What does the \"O\" in BODMAS stand for?",
             "answer": "Orders", "accepted_answers": ["order", "indices", "exponents", "powers"]},
            {"id": "fr-r3", "lo_level": "remember", "difficulty": "easy", "set": 1,
             "question": "In BODMAS, which two operations share equal priority and are performed left to right?",
             "answer": "Division and Multiplication", "accepted_answers": ["multiplication and division"]},
            {"id": "fr-u1", "lo_level": "understand", "difficulty": "easy", "set": 1,
             "question": "BODMAS exists so that everyone gets the ___ answer for the same expression. Fill in the blank.",
             "answer": "same"},
            {"id": "fr-u2", "lo_level": "understand", "difficulty": "medium", "set": 1,
             "question": "Before adding fractions with different denominators, you must first find a common ___. Fill in the blank.",
             "answer": "denominator"},
            {"id": "fr-u3", "lo_level": "understand", "difficulty": "medium", "set": 1,
             "question": "In BODMAS, Division and Multiplication are done left to right because they have ___ priority. Fill in the blank.",
             "answer": "equal"},
            {"id": "fr-a1", "lo_level": "apply", "difficulty": "medium", "set": 1,
             "question": "Evaluate: 2 + 3 x (4 - 1)",
             "answer": "11"},
            {"id": "fr-a2", "lo_level": "apply", "difficulty": "hard", "set": 1,
             "question": "Simplify: 1/2 + 1/3",
             "answer": "5/6", "answer_type": "fraction"},
            {"id": "fr-a3", "lo_level": "apply", "difficulty": "medium", "set": 1,
             "question": "Evaluate: (8 - 2) / 3 + 1",
             "answer": "3"},
            {"id": "fr-n1", "lo_level": "analyze", "difficulty": "medium", "set": 1,
             "question": "What is the correct value of 6 / 2 x 3, following BODMAS' left-to-right rule for division and multiplication?",
             "answer": "9"},
            {"id": "fr-n2", "lo_level": "analyze", "difficulty": "hard", "set": 1,
             "question": "Simplify: 3/4 - 1/6",
             "answer": "7/12", "answer_type": "fraction"},
            {"id": "fr-n3", "lo_level": "analyze", "difficulty": "medium", "set": 1,
             "question": "Evaluate: 5 + (6 - 2) x 2",
             "answer": "13"},
            {"id": "fr-e1", "lo_level": "evaluate", "difficulty": "hard", "set": 1,
             "question": "A classmate claims BODMAS means division always happens before multiplication because D comes before M in the acronym. Is this claim correct? Answer Yes or No.",
             "answer": "No"},
            {"id": "fr-e2", "lo_level": "evaluate", "difficulty": "medium", "set": 1,
             "question": "True or False: In BODMAS, Brackets are always evaluated before Orders (powers/roots).",
             "answer": "True"},
            {"id": "fr-e3", "lo_level": "evaluate", "difficulty": "hard", "set": 1,
             "question": "Which is correct: 3/4 - 1/6 = 7/12, or 3/4 - 1/6 = 1/2? Answer with the correct fraction.",
             "answer": "7/12", "answer_type": "fraction"},
            {"id": "fr-c1", "lo_level": "create", "difficulty": "hard", "set": 1,
             "question": "Complete this word problem so it requires brackets and fraction addition: 'A recipe needs (1/2 + 1/4) cups of flour for one batch. How much flour for ___ batches?' Fill in the SMALLEST whole number of batches that makes the total a whole number of cups.",
             "answer": "4"},
            {"id": "fr-c2", "lo_level": "create", "difficulty": "hard", "set": 1,
             "question": "Fill in the missing number to complete this BODMAS expression so it evaluates to 10: '2 + 4 x ___'",
             "answer": "2"},
            {"id": "fr-c3", "lo_level": "create", "difficulty": "hard", "set": 1,
             "question": "Fill in the missing fraction to complete this word problem with total 1: 'You use 1/3 cup sugar and ___ cup flour, filling a 1-cup container exactly.'",
             "answer": "2/3", "answer_type": "fraction"},
            # ---- Set 2 (retake quiz - different numbers, same structure) ----
            {"id": "fr-r1-2", "lo_level": "remember", "difficulty": "easy", "set": 2,
             "question": "What does the \"M\" in BODMAS stand for?",
             "answer": "Multiplication"},
            {"id": "fr-r2-2", "lo_level": "remember", "difficulty": "easy", "set": 2,
             "question": "What does the \"S\" in BODMAS stand for?",
             "answer": "Subtraction"},
            {"id": "fr-r3-2", "lo_level": "remember", "difficulty": "easy", "set": 2,
             "question": "In BODMAS, which two operations share equal priority and are performed left to right?",
             "answer": "Addition and Subtraction", "accepted_answers": ["subtraction and addition"]},
            {"id": "fr-u1-2", "lo_level": "understand", "difficulty": "easy", "set": 2,
             "question": "If everyone followed a different order of operations, two people evaluating the same expression could get ___ answers. Fill in the blank.",
             "answer": "different"},
            {"id": "fr-u2-2", "lo_level": "understand", "difficulty": "medium", "set": 2,
             "question": "Before subtracting fractions with different denominators, you must first find a common ___. Fill in the blank.",
             "answer": "denominator"},
            {"id": "fr-u3-2", "lo_level": "understand", "difficulty": "medium", "set": 2,
             "question": "In BODMAS, Addition and Subtraction are done left to right because they have ___ priority. Fill in the blank.",
             "answer": "equal"},
            {"id": "fr-a1-2", "lo_level": "apply", "difficulty": "medium", "set": 2,
             "question": "Evaluate: 3 + 2 x (5 - 2)",
             "answer": "9"},
            {"id": "fr-a2-2", "lo_level": "apply", "difficulty": "hard", "set": 2,
             "question": "Simplify: 1/3 + 1/4",
             "answer": "7/12", "answer_type": "fraction"},
            {"id": "fr-a3-2", "lo_level": "apply", "difficulty": "medium", "set": 2,
             "question": "Evaluate: (10 - 4) / 2 + 3",
             "answer": "6"},
            {"id": "fr-n1-2", "lo_level": "analyze", "difficulty": "medium", "set": 2,
             "question": "What is the correct value of 8 - 2 + 3, following BODMAS' left-to-right rule for addition and subtraction?",
             "answer": "9"},
            {"id": "fr-n2-2", "lo_level": "analyze", "difficulty": "hard", "set": 2,
             "question": "Simplify: 5/6 - 1/4",
             "answer": "7/12", "answer_type": "fraction"},
            {"id": "fr-n3-2", "lo_level": "analyze", "difficulty": "medium", "set": 2,
             "question": "Evaluate: 4 + (9 - 3) x 2",
             "answer": "16"},
            {"id": "fr-e1-2", "lo_level": "evaluate", "difficulty": "hard", "set": 2,
             "question": "A classmate claims BODMAS means addition always happens before subtraction because A comes before S in the acronym. Is this claim correct? Answer Yes or No.",
             "answer": "No"},
            {"id": "fr-e2-2", "lo_level": "evaluate", "difficulty": "medium", "set": 2,
             "question": "True or False: In BODMAS, Multiplication and Division must be done strictly left to right, not by which one comes first alphabetically.",
             "answer": "True"},
            {"id": "fr-e3-2", "lo_level": "evaluate", "difficulty": "hard", "set": 2,
             "question": "Which is correct: 5/6 - 1/4 = 7/12, or 5/6 - 1/4 = 2/3? Answer with the correct fraction.",
             "answer": "7/12", "answer_type": "fraction"},
            {"id": "fr-c1-2", "lo_level": "create", "difficulty": "hard", "set": 2,
             "question": "Complete this word problem so it requires brackets and fraction addition: 'A recipe needs (1/3 + 1/6) cups of sugar for one batch. How much sugar for ___ batches?' Fill in the SMALLEST whole number of batches that makes the total a whole number of cups.",
             "answer": "2"},
            {"id": "fr-c2-2", "lo_level": "create", "difficulty": "hard", "set": 2,
             "question": "Fill in the missing number to complete this BODMAS expression so it evaluates to 20: '5 + 3 x ___'",
             "answer": "5"},
            {"id": "fr-c3-2", "lo_level": "create", "difficulty": "hard", "set": 2,
             "question": "Fill in the missing fraction to complete this word problem with total 1: 'You use 1/4 cup milk and ___ cup water, filling a 1-cup container exactly.'",
             "answer": "3/4", "answer_type": "fraction"},
        ],
    },
    "pythagorean-theorem": {
        "title": "Pythagorean Theorem",
        "subject": "Mathematics",
        "questions": [
            {
                "id": "pt-r1", "lo_level": "remember", "difficulty": "easy",
                "question": "In a right triangle, what is the longest side called?",
                "options": ["Hypotenuse", "Adjacent", "Opposite", "Base"],
                "answer": "Hypotenuse",
            },
            {
                "id": "pt-r2", "lo_level": "remember", "difficulty": "easy",
                "question": "What is the Pythagorean theorem formula?",
                "options": ["a^2 + b^2 = c^2", "a + b = c", "a^2 - b^2 = c^2", "a x b = c"],
                "answer": "a^2 + b^2 = c^2",
            },
            {
                "id": "pt-u1", "lo_level": "understand", "difficulty": "easy",
                "question": "Why does the Pythagorean theorem only apply to right triangles?",
                "options": [
                    "The relationship a^2+b^2=c^2 is derived specifically from a 90-degree angle between the two legs",
                    "It applies to all triangles equally",
                    "It's a naming convention with no mathematical reason",
                    "It only works for equilateral triangles",
                ],
                "answer": "The relationship a^2+b^2=c^2 is derived specifically from a 90-degree angle between the two legs",
            },
            {
                "id": "pt-u2", "lo_level": "understand", "difficulty": "medium",
                "question": "If you know the hypotenuse and one leg of a right triangle, how do you find the other leg?",
                "options": ["Rearrange to leg = sqrt(c^2 - a^2)", "Add the two known sides", "Divide the hypotenuse by 2", "It cannot be found"],
                "answer": "Rearrange to leg = sqrt(c^2 - a^2)",
            },
            {
                "id": "pt-a1", "lo_level": "apply", "difficulty": "medium",
                "question": "A right triangle has legs of 3 and 4. What is the hypotenuse?",
                "options": ["5", "6", "7", "12"],
                "answer": "5",
            },
            {
                "id": "pt-a2", "lo_level": "apply", "difficulty": "hard",
                "question": "A ladder leans against a wall, reaching 12m up, with its base 5m from the wall. How long is the ladder?",
                "options": ["13m", "17m", "7m", "60m"],
                "answer": "13m",
            },
            {
                "id": "pt-n1", "lo_level": "analyze", "difficulty": "medium",
                "question": "A triangle has sides 5, 12, and 13. Is it a right triangle? How can you tell?",
                "options": [
                    "Yes, because 5^2 + 12^2 = 13^2",
                    "No, because 5 + 12 is not 13",
                    "Yes, because all sides are different lengths",
                    "Cannot be determined",
                ],
                "answer": "Yes, because 5^2 + 12^2 = 13^2",
            },
            {
                "id": "pt-n2", "lo_level": "analyze", "difficulty": "hard",
                "question": "A sailor uses the Pythagorean theorem to compute distance but consistently gets answers too large. What's the likely error?",
                "options": [
                    "They added the two legs instead of squaring, summing, then taking the square root",
                    "They used too many decimal places",
                    "The theorem is wrong for navigation",
                    "They measured in the wrong units only",
                ],
                "answer": "They added the two legs instead of squaring, summing, then taking the square root",
            },
            {
                "id": "pt-e1", "lo_level": "evaluate", "difficulty": "hard",
                "question": "A student argues the Pythagorean theorem can find the third side of ANY triangle, not just right triangles. What's the strongest counter-argument?",
                "options": [
                    "a^2+b^2=c^2 is only valid when the angle between a and b is exactly 90 degrees; other triangles need the Law of Cosines",
                    "The theorem works for any triangle without exception",
                    "Only equilateral triangles need a different formula",
                    "There is no valid counter-argument",
                ],
                "answer": "a^2+b^2=c^2 is only valid when the angle between a and b is exactly 90 degrees; other triangles need the Law of Cosines",
            },
            {
                "id": "pt-c1", "lo_level": "create", "difficulty": "hard",
                "question": "Design a real-world scenario where the Pythagorean theorem would help find an unknown distance.",
                "options": [
                    "Finding the shortest diagonal path across a rectangular field instead of walking the two edges",
                    "Counting how many students are in a class",
                    "Finding the average of five numbers",
                    "Determining the color of a triangle",
                ],
                "answer": "Finding the shortest diagonal path across a rectangular field instead of walking the two edges",
            },
        ],
    },
    "linear-equations": {
        "title": "Linear Equations",
        "subject": "Mathematics",
        "questions": [
            {
                "id": "le-r1", "lo_level": "remember", "difficulty": "easy",
                "question": "What does \"solving for x\" mean in an equation like 2x + 3 = 9?",
                "options": ["Finding the value of x that makes the equation true", "Finding the value of 2", "Removing x from the equation", "Making the equation longer"],
                "answer": "Finding the value of x that makes the equation true",
            },
            {
                "id": "le-r2", "lo_level": "remember", "difficulty": "easy",
                "question": "What operation undoes addition when isolating a variable?",
                "options": ["Subtraction", "Multiplication", "Division", "Exponentiation"],
                "answer": "Subtraction",
            },
            {
                "id": "le-u1", "lo_level": "understand", "difficulty": "easy",
                "question": "Why must you perform the same operation on both sides of an equation?",
                "options": ["To keep the equation balanced/true", "Because it's a rule with no reason", "To make the equation longer", "It only matters for fractions"],
                "answer": "To keep the equation balanced/true",
            },
            {
                "id": "le-u2", "lo_level": "understand", "difficulty": "medium",
                "question": "What does it mean if solving an equation results in \"0 = 0\"?",
                "options": [
                    "The equation is true for all values of x (infinite solutions)",
                    "There is no solution",
                    "x = 0",
                    "The equation was written incorrectly",
                ],
                "answer": "The equation is true for all values of x (infinite solutions)",
            },
            {
                "id": "le-a1", "lo_level": "apply", "difficulty": "medium",
                "question": "Solve: 3x - 5 = 10",
                "options": ["x = 5", "x = 3", "x = 15", "x = 1.67"],
                "answer": "x = 5",
            },
            {
                "id": "le-a2", "lo_level": "apply", "difficulty": "hard",
                "question": "Solve: 2(x + 3) = 4x - 2",
                "options": ["x = 4", "x = 2", "x = 1", "x = -4"],
                "answer": "x = 4",
            },
            {
                "id": "le-n1", "lo_level": "analyze", "difficulty": "medium",
                "question": "A student solves 5x = 20 and gets x = 100 by multiplying both sides by 5 instead of dividing. What's the error?",
                "options": [
                    "They used the inverse operation incorrectly - multiplication instead of division",
                    "The answer is actually correct",
                    "5x = 20 has no solution",
                    "They should have added 5 instead",
                ],
                "answer": "They used the inverse operation incorrectly - multiplication instead of division",
            },
            {
                "id": "le-n2", "lo_level": "analyze", "difficulty": "hard",
                "question": "Two students solve x/2 + 3 = 7 differently. One gets x = 8, the other gets x = 20. Which is correct and why?",
                "options": [
                    "x = 8, because subtracting 3 first gives x/2 = 4, then multiplying by 2 gives x = 8",
                    "x = 20, because you multiply everything by 2 first without subtracting",
                    "Both are correct",
                    "Neither is correct",
                ],
                "answer": "x = 8, because subtracting 3 first gives x/2 = 4, then multiplying by 2 gives x = 8",
            },
            {
                "id": "le-e1", "lo_level": "evaluate", "difficulty": "hard",
                "question": "A classmate claims you can always solve an equation by guessing and checking rather than using algebraic steps. What's the strongest critique?",
                "options": [
                    "Guessing doesn't scale to equations with large or non-integer solutions and is inefficient",
                    "Guessing is always faster",
                    "Algebraic steps are never necessary",
                    "There's no downside to guessing",
                ],
                "answer": "Guessing doesn't scale to equations with large or non-integer solutions and is inefficient",
            },
            {
                "id": "le-c1", "lo_level": "create", "difficulty": "hard",
                "question": "Design a word problem that requires setting up and solving a linear equation to find an unknown cost.",
                "options": [
                    "A taxi charges a $3 flat fee plus $2 per km. If a ride costs $15, how many km was it?",
                    "What is 3 + 2?",
                    "List all even numbers under 20",
                    "What color is the taxi?",
                ],
                "answer": "A taxi charges a $3 flat fee plus $2 per km. If a ride costs $15, how many km was it?",
            },
        ],
    },
    "algebraic-fractions": {
        "title": "Algebraic Fractions",
        "subject": "Mathematics",
        "questions": [
            {
                "id": "af-r1", "lo_level": "remember", "difficulty": "easy",
                "question": "What is an algebraic fraction?",
                "options": ["A fraction that contains a variable in the numerator, denominator, or both", "A fraction with only numbers", "A whole number", "A fraction with no denominator"],
                "answer": "A fraction that contains a variable in the numerator, denominator, or both",
            },
            {
                "id": "af-r2", "lo_level": "remember", "difficulty": "easy",
                "question": "What value must be excluded from the domain of x/(x-2)?",
                "options": ["x = 2", "x = 0", "x = -2", "x = 1"],
                "answer": "x = 2",
            },
            {
                "id": "af-u1", "lo_level": "understand", "difficulty": "easy",
                "question": "Why can't the denominator of an algebraic fraction equal zero?",
                "options": ["Division by zero is undefined", "It makes the fraction negative", "It's just a convention with no reason", "Zero denominators simplify the fraction"],
                "answer": "Division by zero is undefined",
            },
            {
                "id": "af-u2", "lo_level": "understand", "difficulty": "medium",
                "question": "To simplify (x^2 - 4)/(x - 2), what technique helps?",
                "options": [
                    "Factor the numerator as a difference of squares, then cancel the common factor",
                    "Divide term by term without factoring",
                    "Multiply both parts by 2",
                    "It cannot be simplified",
                ],
                "answer": "Factor the numerator as a difference of squares, then cancel the common factor",
            },
            {
                "id": "af-a1", "lo_level": "apply", "difficulty": "medium",
                "question": "Simplify: (x^2 - 4)/(x - 2)",
                "options": ["x + 2", "x - 2", "x^2 - 2", "2x"],
                "answer": "x + 2",
            },
            {
                "id": "af-a2", "lo_level": "apply", "difficulty": "hard",
                "question": "Simplify: (3x)/(6x^2)",
                "options": ["1/(2x)", "1/2x^2", "3/6x", "2/x"],
                "answer": "1/(2x)",
            },
            {
                "id": "af-n1", "lo_level": "analyze", "difficulty": "medium",
                "question": "A student simplifies (x+2)/(x+4) by cancelling the \"x\" terms to get 2/4 = 1/2. What's wrong with this?",
                "options": [
                    "You can only cancel common factors, not individual terms added together",
                    "The answer is actually correct",
                    "The denominator should have been x-4",
                    "Algebraic fractions cannot be simplified at all",
                ],
                "answer": "You can only cancel common factors, not individual terms added together",
            },
            {
                "id": "af-n2", "lo_level": "analyze", "difficulty": "hard",
                "question": "Why does (x^2 - 9)/(x - 3) simplify to x + 3, but only for x not equal to 3?",
                "options": [
                    "Because factoring cancels (x-3), but the original expression is undefined at x=3, so that restriction must remain",
                    "Because x=3 makes the answer negative",
                    "There is no restriction needed",
                    "Because 9 is a perfect square",
                ],
                "answer": "Because factoring cancels (x-3), but the original expression is undefined at x=3, so that restriction must remain",
            },
            {
                "id": "af-e1", "lo_level": "evaluate", "difficulty": "hard",
                "question": "A classmate claims you can always cancel any matching term that appears in both numerator and denominator. What's the strongest critique?",
                "options": [
                    "Only common factors (multiplied terms) can be cancelled, not terms that are added or subtracted",
                    "The claim is entirely correct",
                    "Cancelling never changes the value of a fraction",
                    "Algebraic fractions don't follow normal fraction rules",
                ],
                "answer": "Only common factors (multiplied terms) can be cancelled, not terms that are added or subtracted",
            },
            {
                "id": "af-c1", "lo_level": "create", "difficulty": "hard",
                "question": "Design a simplification problem that requires factoring a difference of squares before cancelling.",
                "options": ["Simplify (x^2 - 16)/(x - 4)", "Simplify 5/10", "Add 1/2 + 1/2", "Solve x + 4 = 10"],
                "answer": "Simplify (x^2 - 16)/(x - 4)",
            },
        ],
    },
    "volume-capacity": {
        "title": "Volume & Capacity",
        "subject": "Mathematics",
        "questions": [
            {
                "id": "vc-r1", "lo_level": "remember", "difficulty": "easy",
                "question": "What is the formula for the volume of a rectangular box (cuboid)?",
                "options": ["length x breadth x height", "length + breadth + height", "2(length + breadth)", "length x breadth"],
                "answer": "length x breadth x height",
            },
            {
                "id": "vc-r2", "lo_level": "remember", "difficulty": "easy",
                "question": "How many cm3 are in 1 litre?",
                "options": ["1000", "100", "10", "1"],
                "answer": "1000",
            },
            {
                "id": "vc-u1", "lo_level": "understand", "difficulty": "easy",
                "question": "Why is volume measured in cubic units (like cm3)?",
                "options": [
                    "Because it represents three dimensions multiplied together (length x breadth x height)",
                    "Because it's a rule with no reason",
                    "Cubic units only apply to cubes",
                    "Volume is always measured in litres only",
                ],
                "answer": "Because it represents three dimensions multiplied together (length x breadth x height)",
            },
            {
                "id": "vc-u2", "lo_level": "understand", "difficulty": "medium",
                "question": "What's the relationship between cm3 and litres when reporting a container's capacity?",
                "options": [
                    "Divide the cm3 value by 1000 to convert to litres",
                    "Multiply the cm3 value by 1000 to convert to litres",
                    "They are unrelated units",
                    "Litres are always smaller than cm3",
                ],
                "answer": "Divide the cm3 value by 1000 to convert to litres",
            },
            {
                "id": "vc-a1", "lo_level": "apply", "difficulty": "medium",
                "question": "A fish tank is 40cm x 25cm x 30cm. What is its volume in cm3?",
                "options": ["30000", "3000", "950", "95"],
                "answer": "30000",
            },
            {
                "id": "vc-a2", "lo_level": "apply", "difficulty": "hard",
                "question": "A tank has a volume of 45000 cm3. How many litres of water does it hold?",
                "options": ["45", "4.5", "450", "4500"],
                "answer": "45",
            },
            {
                "id": "vc-n1", "lo_level": "analyze", "difficulty": "medium",
                "question": "Two tanks have the same volume but different dimensions - one tall and narrow, the other short and wide. Why can they hold the same amount of water?",
                "options": [
                    "Volume depends on the product of all three dimensions, not their individual shape",
                    "Only height determines capacity",
                    "Wider tanks always hold more regardless of height",
                    "They cannot actually hold the same amount",
                ],
                "answer": "Volume depends on the product of all three dimensions, not their individual shape",
            },
            {
                "id": "vc-n2", "lo_level": "analyze", "difficulty": "hard",
                "question": "A shop sells a tank advertised as \"50 litres\" but a customer calculates its dimensions give 45000 cm3. What should the customer conclude?",
                "options": [
                    "The advertised capacity is wrong - 45000 cm3 equals 45 litres, not 50",
                    "The advertisement is correct because litres and cm3 aren't comparable",
                    "The tank must be a different shape than measured",
                    "There's no way to check this",
                ],
                "answer": "The advertised capacity is wrong - 45000 cm3 equals 45 litres, not 50",
            },
            {
                "id": "vc-e1", "lo_level": "evaluate", "difficulty": "hard",
                "question": "A customer claims doubling a tank's height alone will double its capacity, but doubling its length won't. What's the strongest critique?",
                "options": [
                    "Doubling ANY single dimension (length, breadth, or height) doubles the volume equally, since volume is their product",
                    "The claim is completely correct",
                    "Only width matters for capacity",
                    "Doubling any dimension quadruples volume",
                ],
                "answer": "Doubling ANY single dimension (length, breadth, or height) doubles the volume equally, since volume is their product",
            },
            {
                "id": "vc-c1", "lo_level": "create", "difficulty": "hard",
                "question": "Design a real-world task that requires calculating volume and converting to litres to solve.",
                "options": [
                    "Determine how many litres of water are needed to fill a fish tank of given length, breadth, and height",
                    "Count how many fish are in the tank",
                    "Measure the temperature of the water",
                    "List fish species suitable for the tank",
                ],
                "answer": "Determine how many litres of water are needed to fill a fish tank of given length, breadth, and height",
            },
        ],
    },
    "number-patterns": {
        "title": "Number Patterns",
        "subject": "Mathematics",
        "questions": [
            {
                "id": "np-r1", "lo_level": "remember", "difficulty": "easy",
                "question": "In the sequence 2, 5, 8, 11, ..., what is the common difference?",
                "options": ["3", "2", "5", "4"],
                "answer": "3",
            },
            {
                "id": "np-r2", "lo_level": "remember", "difficulty": "easy",
                "question": "What does \"Tn\" typically represent in a number pattern?",
                "options": ["The general (nth) term of the sequence", "The total of all terms", "The first term only", "The number of terms"],
                "answer": "The general (nth) term of the sequence",
            },
            {
                "id": "np-u1", "lo_level": "understand", "difficulty": "easy",
                "question": "Why is finding the general term Tn useful for a sequence?",
                "options": [
                    "It lets you find any term directly without listing every previous term",
                    "It only works for the first term",
                    "It replaces the need for sequences entirely",
                    "It only applies to even-numbered sequences",
                ],
                "answer": "It lets you find any term directly without listing every previous term",
            },
            {
                "id": "np-u2", "lo_level": "understand", "difficulty": "medium",
                "question": "For an arithmetic sequence with first term a and common difference d, what is the general formula for Tn?",
                "options": ["Tn = a + (n-1)d", "Tn = a x d x n", "Tn = a + n", "Tn = a - (n-1)d"],
                "answer": "Tn = a + (n-1)d",
            },
            {
                "id": "np-a1", "lo_level": "apply", "difficulty": "medium",
                "question": "For the sequence 4, 7, 10, 13, ..., what is the 10th term?",
                "options": ["31", "28", "34", "25"],
                "answer": "31",
            },
            {
                "id": "np-a2", "lo_level": "apply", "difficulty": "hard",
                "question": "A sequence has Tn = 3n - 2. What is T7?",
                "options": ["19", "21", "17", "23"],
                "answer": "19",
            },
            {
                "id": "np-n1", "lo_level": "analyze", "difficulty": "medium",
                "question": "A student thinks the sequence 1, 4, 9, 16, ... has a constant common difference. Why is this wrong?",
                "options": [
                    "The differences between terms (3, 5, 7...) increase, so it's not arithmetic - it's a squared-number pattern",
                    "The common difference is actually 3 for all terms",
                    "All sequences have a constant difference",
                    "The sequence is decreasing",
                ],
                "answer": "The differences between terms (3, 5, 7...) increase, so it's not arithmetic - it's a squared-number pattern",
            },
            {
                "id": "np-n2", "lo_level": "analyze", "difficulty": "hard",
                "question": "Given Tn = 2n + 1, a student claims T0 = 1 is a valid term of a sequence starting at n=1. What's the issue?",
                "options": [
                    "If the sequence starts at n=1, then n=0 is outside its defined domain and isn't a valid term",
                    "T0 is always the first term of any sequence",
                    "There is no issue, T0 is correct",
                    "The formula is wrong",
                ],
                "answer": "If the sequence starts at n=1, then n=0 is outside its defined domain and isn't a valid term",
            },
            {
                "id": "np-e1", "lo_level": "evaluate", "difficulty": "hard",
                "question": "A classmate claims that any three numbers can be extended into a unique valid number pattern. What's the strongest critique?",
                "options": [
                    "Multiple different patterns/rules can fit the same three numbers, so the \"next\" term isn't uniquely determined without more info",
                    "Three numbers always uniquely determine a pattern",
                    "Patterns require at least ten numbers to exist",
                    "There's no valid critique",
                ],
                "answer": "Multiple different patterns/rules can fit the same three numbers, so the \"next\" term isn't uniquely determined without more info",
            },
            {
                "id": "np-c1", "lo_level": "create", "difficulty": "hard",
                "question": "Design a number pattern puzzle where students must find both the common difference and the general term Tn.",
                "options": [
                    "Given the sequence 6, 11, 16, 21, find the common difference and write a formula for the nth term",
                    "List the first five prime numbers",
                    "What is 6 + 11?",
                    "Draw a picture of a number line",
                ],
                "answer": "Given the sequence 6, 11, 16, 21, find the common difference and write a formula for the nth term",
            },
        ],
    },
    "area-of-shapes": {
        "title": "Area of Squares, Rectangles & Triangles",
        "subject": "Mathematics",
        "questions": [
            {
                "id": "ar-r1", "lo_level": "remember", "difficulty": "easy",
                "question": "What is the formula for the area of a square with side length a?",
                "options": ["a x a", "4 x a", "a + a", "a / 2"],
                "answer": "a x a",
            },
            {
                "id": "ar-r2", "lo_level": "remember", "difficulty": "easy",
                "question": "What is the formula for the area of a rectangle with length l and breadth b?",
                "options": ["l x b", "2(l + b)", "l + b", "l / b"],
                "answer": "l x b",
            },
            {
                "id": "ar-u1", "lo_level": "understand", "difficulty": "easy",
                "question": "Why is a triangle's area calculated as 0.5 x base x height rather than base x height?",
                "options": [
                    "A triangle is exactly half of a rectangle/parallelogram with the same base and height",
                    "It's an arbitrary rule with no reason",
                    "Triangles have less area by definition",
                    "base x height always overestimates every shape by exactly 2x",
                ],
                "answer": "A triangle is exactly half of a rectangle/parallelogram with the same base and height",
            },
            {
                "id": "ar-u2", "lo_level": "understand", "difficulty": "medium",
                "question": "If a rectangle and a square have the same area, what must be true?",
                "options": [
                    "The rectangle's length x breadth equals the square's side x side",
                    "They must have identical side lengths",
                    "The square must always be smaller",
                    "There is no relationship between the two",
                ],
                "answer": "The rectangle's length x breadth equals the square's side x side",
            },
            {
                "id": "ar-a1", "lo_level": "apply", "difficulty": "medium",
                "question": "A square plot has a side of 9 meters. What is its area?",
                "options": ["81 sqm", "36 sqm", "18 sqm", "90 sqm"],
                "answer": "81 sqm",
            },
            {
                "id": "ar-a2", "lo_level": "apply", "difficulty": "hard",
                "question": "A rectangular plot is 12m long and 5m wide. What is its area?",
                "options": ["60 sqm", "17 sqm", "24 sqm", "30 sqm"],
                "answer": "60 sqm",
            },
            {
                "id": "ar-n1", "lo_level": "analyze", "difficulty": "medium",
                "question": "A student calculates a triangular plot's area as base x height instead of 0.5 x base x height, using base=10m and height=6m. What's the mistake and the correct area?",
                "options": [
                    "Forgot to halve it - correct area is 30 sqm, not 60",
                    "Used the wrong base - correct area is 16 sqm",
                    "The calculation is actually correct at 60 sqm",
                    "Triangles don't have area",
                ],
                "answer": "Forgot to halve it - correct area is 30 sqm, not 60",
            },
            {
                "id": "ar-n2", "lo_level": "analyze", "difficulty": "hard",
                "question": "A rectangular plot (6m x 4m) has an area of 24 sqm. Can a square plot with a whole-number side length also have an area of exactly 24 sqm?",
                "options": [
                    "No - no whole number squared equals 24 (4 squared=16, 5 squared=25)",
                    "Yes - side length 6",
                    "Yes - side length 12",
                    "Squares can never equal 24 sqm under any circumstances",
                ],
                "answer": "No - no whole number squared equals 24 (4 squared=16, 5 squared=25)",
            },
            {
                "id": "ar-e1", "lo_level": "evaluate", "difficulty": "hard",
                "question": "A land agent shows a triangle plot with base=20m, height=2m, claiming it's \"huge\" because the base is long. What's the strongest critique?",
                "options": [
                    "Area depends on base x height together (only 20 sqm here) - a long base with a short height can still have less area than a smaller, more balanced triangle",
                    "Triangles are always bigger than rectangles",
                    "The base length alone determines the area",
                    "There is no valid critique - a bigger base always means bigger area",
                ],
                "answer": "Area depends on base x height together (only 20 sqm here) - a long base with a short height can still have less area than a smaller, more balanced triangle",
            },
            {
                "id": "ar-c1", "lo_level": "create", "difficulty": "hard",
                "question": "Design a way to check whether a rectangular plot advertised as \"40 square meters\" with a length of 10m is correctly measured, without re-measuring the whole plot.",
                "options": [
                    "Divide 40 by the stated length (10m) to get the expected breadth (4m), then verify just that one measurement",
                    "Multiply 40 by 10",
                    "Assume the advertisement is always correct",
                    "There is no way to check this",
                ],
                "answer": "Divide 40 by the stated length (10m) to get the expected breadth (4m), then verify just that one measurement",
            },
        ],
    },
    "triangle-angle-theorems": {
        "title": "Triangle Angle Theorems",
        "subject": "Mathematics",
        "questions": [
            {
                "id": "ta-r1", "lo_level": "remember", "difficulty": "easy",
                "question": "What is the sum of the interior angles of any triangle?",
                "options": ["180 degrees", "360 degrees", "90 degrees", "270 degrees"],
                "answer": "180 degrees",
            },
            {
                "id": "ta-r2", "lo_level": "remember", "difficulty": "easy",
                "question": "What does the Exterior Angle Theorem state?",
                "options": [
                    "An exterior angle equals the sum of the two remote interior angles",
                    "An exterior angle equals the third interior angle",
                    "All exterior angles are 90 degrees",
                    "Exterior angles always equal 180 degrees",
                ],
                "answer": "An exterior angle equals the sum of the two remote interior angles",
            },
            {
                "id": "ta-u1", "lo_level": "understand", "difficulty": "easy",
                "question": "Why do the interior angles of a triangle always add up to 180 degrees, regardless of its shape?",
                "options": [
                    "It follows from parallel-line angle relationships when a line through one vertex is drawn parallel to the opposite side",
                    "It's a rule that only applies to right triangles",
                    "Triangles are simply defined to always equal 180 degrees with no underlying reason",
                    "It only applies to equilateral triangles",
                ],
                "answer": "It follows from parallel-line angle relationships when a line through one vertex is drawn parallel to the opposite side",
            },
            {
                "id": "ta-u2", "lo_level": "understand", "difficulty": "medium",
                "question": "Why is an exterior angle always larger than either of its two remote interior angles?",
                "options": [
                    "Because the exterior angle equals their sum, and adding two positive angles gives something bigger than either one alone",
                    "Exterior angles are defined to always be 180 degrees",
                    "It's a coincidence with no underlying reason",
                    "Exterior angles are always exactly double the largest interior angle",
                ],
                "answer": "Because the exterior angle equals their sum, and adding two positive angles gives something bigger than either one alone",
            },
            {
                "id": "ta-a1", "lo_level": "apply", "difficulty": "medium",
                "question": "A triangle has interior angles of 55 degrees and 65 degrees. What is the third angle?",
                "options": ["60 degrees", "70 degrees", "50 degrees", "55 degrees"],
                "answer": "60 degrees",
            },
            {
                "id": "ta-a2", "lo_level": "apply", "difficulty": "hard",
                "question": "An exterior angle of a triangle is 110 degrees. One remote interior angle is 45 degrees. What is the other one, x?",
                "options": ["65 degrees", "55 degrees", "70 degrees", "45 degrees"],
                "answer": "65 degrees",
            },
            {
                "id": "ta-n1", "lo_level": "analyze", "difficulty": "medium",
                "question": "A student says a triangle with an exterior angle of 140 degrees and remote interior angles of 70 and 70 degrees must be right-angled at the third vertex. Are they correct?",
                "options": [
                    "No - the interior angle at that vertex is 180 - 140 = 40 degrees, not 90 degrees",
                    "Yes, that's exactly a right angle",
                    "The angles given are impossible for a triangle",
                    "There isn't enough information to tell",
                ],
                "answer": "No - the interior angle at that vertex is 180 - 140 = 40 degrees, not 90 degrees",
            },
            {
                "id": "ta-n2", "lo_level": "analyze", "difficulty": "hard",
                "question": "A triangle has interior angles of 90, 45, and 45 degrees. Student A says it's isosceles. Student B says it can't be, since a right triangle can't have two equal sides. Who is correct?",
                "options": [
                    "Student A - two equal angles (45 and 45) mean two equal sides, so it is isosceles regardless of also having a right angle",
                    "Student B - right triangles can never be isosceles",
                    "Neither - isosceles triangles can't have a right angle in them at all",
                    "The triangle described doesn't actually exist",
                ],
                "answer": "Student A - two equal angles (45 and 45) mean two equal sides, so it is isosceles regardless of also having a right angle",
            },
            {
                "id": "ta-e1", "lo_level": "evaluate", "difficulty": "hard",
                "question": "A classmate claims the Exterior Angle Theorem makes the Angle Sum Theorem (180 degrees) unnecessary, since you can always use exterior angles instead. What's the strongest critique?",
                "options": [
                    "The Exterior Angle Theorem is itself derived from the Angle Sum Theorem, and you still need the 180-degree rule directly whenever no exterior angle is given at all",
                    "The Angle Sum Theorem is actually incorrect",
                    "Exterior angles don't really exist in real triangles",
                    "Both theorems give different, contradictory answers for the same triangle",
                ],
                "answer": "The Exterior Angle Theorem is itself derived from the Angle Sum Theorem, and you still need the 180-degree rule directly whenever no exterior angle is given at all",
            },
            {
                "id": "ta-c1", "lo_level": "create", "difficulty": "hard",
                "question": "Design a real-world scenario where measuring an exterior angle, rather than the interior angle, is the practical way to find a missing triangle angle.",
                "options": [
                    "A surveyor stands outside a triangular plot and can only measure the angle where one boundary line extends past a corner, not the inside angle itself",
                    "Measuring the length of one side of a plot",
                    "Counting how many corners the plot has",
                    "Painting the triangular plot a different color",
                ],
                "answer": "A surveyor stands outside a triangular plot and can only measure the angle where one boundary line extends past a corner, not the inside angle itself",
            },
        ],
    },
    "algebraic-expressions": {
        "title": "Algebraic Expressions",
        "subject": "Mathematics",
        "questions": [
            {
                "id": "ae-r1", "lo_level": "remember", "difficulty": "easy",
                "question": "What does it mean to \"simplify\" an algebraic expression like 3x + 2x?",
                "options": [
                    "Combine like terms into a single term (5x)",
                    "Multiply all the terms together",
                    "Substitute a number for x",
                    "Factor it into two brackets",
                ],
                "answer": "Combine like terms into a single term (5x)",
            },
            {
                "id": "ae-r2", "lo_level": "remember", "difficulty": "easy",
                "question": "What is a \"like term\" in algebra?",
                "options": [
                    "Terms with the same variable raised to the same power (e.g. 3x and 5x)",
                    "Any two numbers",
                    "Terms that have the same sign",
                    "Terms written in the same color",
                ],
                "answer": "Terms with the same variable raised to the same power (e.g. 3x and 5x)",
            },
            {
                "id": "ae-u1", "lo_level": "understand", "difficulty": "easy",
                "question": "Why can you add 3x and 5x directly to get 8x, but you can't add 3x and 5x^2 directly?",
                "options": [
                    "3x and 5x have the same variable and power, but x and x^2 are different powers, so they aren't like terms",
                    "Addition never works with variables",
                    "x^2 is always bigger so it can't be added",
                    "You actually can add them to get 8x^2",
                ],
                "answer": "3x and 5x have the same variable and power, but x and x^2 are different powers, so they aren't like terms",
            },
            {
                "id": "ae-u2", "lo_level": "understand", "difficulty": "medium",
                "question": "Why does factorizing x^2 + 5x + 6 into (x+2)(x+3) give an equivalent expression?",
                "options": [
                    "Expanding (x+2)(x+3) using the distributive law gives back x^2 + 5x + 6 exactly",
                    "Factorizing always changes the value of an expression",
                    "It's just a shorter way to write it with no mathematical relationship",
                    "Only some quadratics can be checked this way",
                ],
                "answer": "Expanding (x+2)(x+3) using the distributive law gives back x^2 + 5x + 6 exactly",
            },
            {
                "id": "ae-a1", "lo_level": "apply", "difficulty": "medium",
                "question": "Simplify: 4y + 3y - 2 + 6",
                "options": ["7y + 4", "7y + 2", "4y + 4", "7y - 4"],
                "answer": "7y + 4",
            },
            {
                "id": "ae-a2", "lo_level": "apply", "difficulty": "hard",
                "question": "Multiply: 2x(x + 5)",
                "options": ["2x^2 + 10x", "2x^2 + 5x", "2x + 10x", "x^2 + 10x"],
                "answer": "2x^2 + 10x",
            },
            {
                "id": "ae-n1", "lo_level": "analyze", "difficulty": "medium",
                "question": "A student simplifies 3x + 2x^2 as 5x^2. What mistake did they make?",
                "options": [
                    "They treated 3x and 2x^2 as like terms and added them, even though x and x^2 are different powers - it's already fully simplified as 3x + 2x^2",
                    "They forgot to multiply the terms",
                    "The answer 5x^2 is actually correct",
                    "x^2 always equals x",
                ],
                "answer": "They treated 3x and 2x^2 as like terms and added them, even though x and x^2 are different powers - it's already fully simplified as 3x + 2x^2",
            },
            {
                "id": "ae-n2", "lo_level": "analyze", "difficulty": "hard",
                "question": "Two students factorize x^2 + 7x + 12 differently: one gets (x+3)(x+4), the other gets (x+2)(x+6). Which is correct, and how can you check?",
                "options": [
                    "(x+3)(x+4) is correct - expanding it gives x^2+7x+12, while (x+2)(x+6) expands to x^2+8x+12, which doesn't match",
                    "(x+2)(x+6) is correct because 2 times 6 = 12",
                    "Both are correct since they both multiply to 12",
                    "Neither is correct",
                ],
                "answer": "(x+3)(x+4) is correct - expanding it gives x^2+7x+12, while (x+2)(x+6) expands to x^2+8x+12, which doesn't match",
            },
            {
                "id": "ae-e1", "lo_level": "evaluate", "difficulty": "hard",
                "question": "A classmate claims that substituting x=2 into 4x^2 - 3x + 1 gives the same result no matter what order you apply the operations. What's the strongest response?",
                "options": [
                    "Order of operations still applies during substitution - square first, then multiply, then subtract, then add, in the correct order, or you'll get a wrong answer",
                    "The claim is completely true, order never matters",
                    "Substitution doesn't involve any order of operations",
                    "Squaring and multiplying always give the same result",
                ],
                "answer": "Order of operations still applies during substitution - square first, then multiply, then subtract, then add, in the correct order, or you'll get a wrong answer",
            },
            {
                "id": "ae-c1", "lo_level": "create", "difficulty": "hard",
                "question": "Design a real-world word problem that requires substituting a value into the algebraic expression 5x + 20 to find a total cost.",
                "options": [
                    "A taxi charges a $20 booking fee plus $5 per km - what's the total cost for a 6 km ride?",
                    "What is 5 + 20?",
                    "List multiples of 5",
                    "Draw a graph of a circle",
                ],
                "answer": "A taxi charges a $20 booking fee plus $5 per km - what's the total cost for a 6 km ride?",
            },
        ],
    },
    "rounding-off": {
        "title": "Rounding Off Numbers",
        "subject": "Mathematics",
        "questions": [
            {
                "id": "ro-r1", "lo_level": "remember", "difficulty": "easy",
                "question": "When rounding, what do you do if the digit right after the rounding place is 5 or more?",
                "options": ["Round up", "Round down", "Leave it unchanged", "Add a zero"],
                "answer": "Round up",
            },
            {
                "id": "ro-r2", "lo_level": "remember", "difficulty": "easy",
                "question": "What does it mean to round a number to 3 significant figures?",
                "options": [
                    "Keep only the first 3 meaningful digits (starting from the first non-zero digit), rounding the rest",
                    "Keep only the first 3 digits after the decimal point",
                    "Round to the nearest thousand",
                    "Keep exactly 3 digits before the decimal point",
                ],
                "answer": "Keep only the first 3 meaningful digits (starting from the first non-zero digit), rounding the rest",
            },
            {
                "id": "ro-u1", "lo_level": "understand", "difficulty": "easy",
                "question": "Why does rounding 1,346 to the nearest 100 give 1,300 and not 1,400?",
                "options": [
                    "The tens digit (4) is less than 5, so the hundreds digit stays the same instead of rounding up",
                    "1,346 is closer to 1,400 on the number line",
                    "You always round down for even numbers",
                    "There's no reason, it's arbitrary",
                ],
                "answer": "The tens digit (4) is less than 5, so the hundreds digit stays the same instead of rounding up",
            },
            {
                "id": "ro-u2", "lo_level": "understand", "difficulty": "medium",
                "question": "Why do leading zeros (like the 0.00 in 0.004567) not count as significant figures?",
                "options": [
                    "Leading zeros only show the size/position of the number, they don't add precision about the measured value",
                    "Leading zeros are actually always significant",
                    "Zeros are never allowed in significant figures",
                    "It's a rule with no underlying reason",
                ],
                "answer": "Leading zeros only show the size/position of the number, they don't add precision about the measured value",
            },
            {
                "id": "ro-a1", "lo_level": "apply", "difficulty": "medium",
                "question": "Round 683 to the nearest 10.",
                "options": ["680", "690", "700", "600"],
                "answer": "680",
            },
            {
                "id": "ro-a2", "lo_level": "apply", "difficulty": "hard",
                "question": "Round 12.3456 to 3 decimal places.",
                "options": ["12.346", "12.345", "12.34", "12.35"],
                "answer": "12.346",
            },
            {
                "id": "ro-n1", "lo_level": "analyze", "difficulty": "medium",
                "question": "A student rounds 1,349 to the nearest 100 and gets 1,400 by rounding the tens digit (4) up because \"it's close to 5\". What's the mistake?",
                "options": [
                    "Only the actual digit value matters, not how \"close\" it feels - 4 is less than 5, so it rounds down to 1,300",
                    "The student's answer of 1,400 is actually correct",
                    "1,349 cannot be rounded to the nearest 100 at all",
                    "You should round the ones digit instead of the tens digit",
                ],
                "answer": "Only the actual digit value matters, not how \"close\" it feels - 4 is less than 5, so it rounds down to 1,300",
            },
            {
                "id": "ro-n2", "lo_level": "analyze", "difficulty": "hard",
                "question": "Two students round 0.04999 to 2 significant figures. One gets 0.050, the other gets 0.049. Which is correct?",
                "options": [
                    "0.050 - the third significant figure (9) rounds the second (4) up to 5, and the trailing zero shows the precision",
                    "0.049 - you should just remove the extra digits without rounding",
                    "Both are equally correct",
                    "Neither is correct - 0.04999 cannot be rounded",
                ],
                "answer": "0.050 - the third significant figure (9) rounds the second (4) up to 5, and the trailing zero shows the precision",
            },
            {
                "id": "ro-e1", "lo_level": "evaluate", "difficulty": "hard",
                "question": "A classmate claims rounding a price up for a \"quick estimate\" is always more useful than rounding to the nearest value. What's the strongest critique?",
                "options": [
                    "Always rounding up systematically overestimates totals, which can be just as misleading as underestimating - rounding to the nearest value gives the fairest quick estimate",
                    "The claim is completely correct in every situation",
                    "Rounding down is always better instead",
                    "Estimates are never useful in real life",
                ],
                "answer": "Always rounding up systematically overestimates totals, which can be just as misleading as underestimating - rounding to the nearest value gives the fairest quick estimate",
            },
            {
                "id": "ro-c1", "lo_level": "create", "difficulty": "hard",
                "question": "Design a real-world scenario where rounding a measurement to the nearest 1000 would be practical, but rounding to the nearest 10 would not.",
                "options": [
                    "Estimating a country's total population for a news headline, where exact precision isn't needed and huge numbers are easier to read rounded",
                    "Measuring the exact dose of medicine for a patient",
                    "Recording the winning time in a 100m sprint race",
                    "Cutting a piece of wood to an exact length for furniture",
                ],
                "answer": "Estimating a country's total population for a news headline, where exact precision isn't needed and huge numbers are easier to read rounded",
            },
        ],
    },
    "parallel-line-angles": {
        "title": "Parallel Lines and Angle Properties",
        "subject": "Mathematics",
        "questions": [
            {
                "id": "pl-r1", "lo_level": "remember", "difficulty": "easy",
                "question": "When two parallel lines are cut by a transversal, what is true about corresponding angles?",
                "options": ["They are equal", "They add up to 180 degrees", "They add up to 90 degrees", "They are always right angles"],
                "answer": "They are equal",
            },
            {
                "id": "pl-r2", "lo_level": "remember", "difficulty": "easy",
                "question": "What is true about co-interior (allied) angles between two parallel lines?",
                "options": ["They add up to 180 degrees", "They are equal", "They add up to 90 degrees", "They are always equal to 45 degrees"],
                "answer": "They add up to 180 degrees",
            },
            {
                "id": "pl-u1", "lo_level": "understand", "difficulty": "easy",
                "question": "Why are alternate interior angles equal when two lines are truly parallel, but not when the lines aren't parallel?",
                "options": [
                    "The equality of alternate angles is a direct consequence of the lines being parallel - it doesn't hold for non-parallel lines",
                    "Alternate angles are always equal no matter what, even for non-parallel lines",
                    "It's just a naming convention with no geometric reason",
                    "Alternate angles only exist when lines are parallel",
                ],
                "answer": "The equality of alternate angles is a direct consequence of the lines being parallel - it doesn't hold for non-parallel lines",
            },
            {
                "id": "pl-u2", "lo_level": "understand", "difficulty": "medium",
                "question": "Why do vertically opposite angles stay equal regardless of whether any lines involved are parallel?",
                "options": [
                    "Vertically opposite angles come from two straight lines crossing at a point - that relationship doesn't depend on any other line being parallel to anything",
                    "Vertically opposite angles are only equal when a transversal crosses parallel lines",
                    "It's a special case of the co-interior angle rule",
                    "Vertically opposite angles are never actually equal",
                ],
                "answer": "Vertically opposite angles come from two straight lines crossing at a point - that relationship doesn't depend on any other line being parallel to anything",
            },
            {
                "id": "pl-a1", "lo_level": "apply", "difficulty": "medium",
                "question": "Two parallel lines are cut by a transversal. One angle is 78 degrees. What is its corresponding angle?",
                "options": ["78 degrees", "102 degrees", "180 degrees", "39 degrees"],
                "answer": "78 degrees",
            },
            {
                "id": "pl-a2", "lo_level": "apply", "difficulty": "hard",
                "question": "Two parallel lines are cut by a transversal. One angle is 95 degrees. What is its co-interior angle?",
                "options": ["85 degrees", "95 degrees", "180 degrees", "5 degrees"],
                "answer": "85 degrees",
            },
            {
                "id": "pl-n1", "lo_level": "analyze", "difficulty": "medium",
                "question": "A student says two angles measuring 80 degrees and 100 degrees at a parallel-line crossing must be alternate angles because they're both marked between the lines. What's the issue?",
                "options": [
                    "Alternate angles must be EQUAL - 80 and 100 aren't equal, so they're more likely co-interior angles (which do sum to 180)",
                    "Alternate angles can be any two different values",
                    "The student is completely correct",
                    "Being between the lines automatically makes them alternate angles",
                ],
                "answer": "Alternate angles must be EQUAL - 80 and 100 aren't equal, so they're more likely co-interior angles (which do sum to 180)",
            },
            {
                "id": "pl-n2", "lo_level": "analyze", "difficulty": "hard",
                "question": "At one intersection of a transversal and a parallel line, one angle is 130 degrees. A student claims the vertically opposite angle AND the adjacent angle on the straight line are both 50 degrees. Is this possible?",
                "options": [
                    "No - the vertically opposite angle equals 130 degrees (not 50), while the adjacent angle on the straight line is 50 degrees (180-130) - only one of those two claims is correct",
                    "Yes, both are correct",
                    "No, neither can be 50 degrees",
                    "There isn't enough information to tell",
                ],
                "answer": "No - the vertically opposite angle equals 130 degrees (not 50), while the adjacent angle on the straight line is 50 degrees (180-130) - only one of those two claims is correct",
            },
            {
                "id": "pl-e1", "lo_level": "evaluate", "difficulty": "hard",
                "question": "A classmate claims that once you know ONE angle at a parallel-line crossing, you automatically know all 8 angles formed by the transversal. What's the strongest evaluation of this claim?",
                "options": [
                    "It's true - with true parallel lines and one transversal, every angle is either equal to the known one or its supplement (180 minus it), so one value determines all 8",
                    "It's false - you need at least 2 given angles to know the rest",
                    "It's false - parallel lines don't create any predictable angle relationships",
                    "It's only true for right angles",
                ],
                "answer": "It's true - with true parallel lines and one transversal, every angle is either equal to the known one or its supplement (180 minus it), so one value determines all 8",
            },
            {
                "id": "pl-c1", "lo_level": "create", "difficulty": "hard",
                "question": "Design a real-world scenario where recognizing co-interior angles between parallel lines would help solve a practical problem.",
                "options": [
                    "A carpenter checks that two shelves are parallel by measuring that the angles a support beam makes with each shelf add up to 180 degrees",
                    "Counting the number of shelves in a bookcase",
                    "Painting two shelves the same color",
                    "Measuring the weight a shelf can hold",
                ],
                "answer": "A carpenter checks that two shelves are parallel by measuring that the angles a support beam makes with each shelf add up to 180 degrees",
            },
        ],
    },
    "fraction-operations": {
        "title": "Fraction Operations: Simplify, Combine & Compare",
        "subject": "Mathematics",
        "questions": [
            # ---- Set 1 ----
            {"id": "fc-r1", "lo_level": "remember", "difficulty": "easy", "set": 1,
             "question": "In the fraction 3/4, what is the number 4 called?",
             "answer": "denominator"},
            {"id": "fc-r2", "lo_level": "remember", "difficulty": "easy", "set": 1,
             "question": "What is the reciprocal of 2/5?",
             "answer": "5/2", "answer_type": "fraction"},
            {"id": "fc-r3", "lo_level": "remember", "difficulty": "easy", "set": 1,
             "question": "To simplify a fraction, you divide the numerator and denominator by their greatest common what?",
             "answer": "factor", "accepted_answers": ["gcf", "greatest common factor", "common factor"]},
            {"id": "fc-u1", "lo_level": "understand", "difficulty": "easy", "set": 1,
             "question": "Before adding fractions with different denominators, you must first find a common ___. Fill in the blank.",
             "answer": "denominator"},
            {"id": "fc-u2", "lo_level": "understand", "difficulty": "medium", "set": 1,
             "question": "Dividing by a fraction is the same as multiplying by its ___. Fill in the blank.",
             "answer": "reciprocal"},
            {"id": "fc-u3", "lo_level": "understand", "difficulty": "medium", "set": 1,
             "question": "6/8 simplifies to 3/4 because both 6 and 8 share a common factor of ___. Fill in the blank with a number.",
             "answer": "2"},
            {"id": "fc-a1", "lo_level": "apply", "difficulty": "medium", "set": 1,
             "question": "Simplify 12/16.",
             "answer": "3/4", "answer_type": "fraction"},
            {"id": "fc-a2", "lo_level": "apply", "difficulty": "medium", "set": 1,
             "question": "Evaluate: 3/5 x 2/3",
             "answer": "2/5", "answer_type": "fraction"},
            {"id": "fc-a3", "lo_level": "apply", "difficulty": "medium", "set": 1,
             "question": "Evaluate: 4/9 / (2/3)",
             "answer": "2/3", "answer_type": "fraction"},
            {"id": "fc-n1", "lo_level": "analyze", "difficulty": "medium", "set": 1,
             "question": "A recipe needs 5/6 cup flour. You've already added 1/2 cup. How much more do you need?",
             "answer": "1/3", "answer_type": "fraction"},
            {"id": "fc-n2", "lo_level": "analyze", "difficulty": "hard", "set": 1,
             "question": "You have 7/8 liter of milk. Each bottle holds 1/4 liter. How many FULL bottles can you fill (ignore any leftover)?",
             "answer": "3"},
            {"id": "fc-n3", "lo_level": "analyze", "difficulty": "medium", "set": 1,
             "question": "A garden bed is divided into 10 equal parts. 6 parts have tomatoes and the rest have peppers. What fraction (simplified) of the bed has peppers?",
             "answer": "2/5", "answer_type": "fraction"},
            {"id": "fc-e1", "lo_level": "evaluate", "difficulty": "hard", "set": 1,
             "question": "Compare 5/8 and 3/4. Which is larger? Answer with the larger fraction.",
             "answer": "3/4", "answer_type": "fraction"},
            {"id": "fc-e2", "lo_level": "evaluate", "difficulty": "hard", "set": 1,
             "question": "By how much is 3/4 larger than 5/8? Give the simplest fraction.",
             "answer": "1/8", "answer_type": "fraction"},
            {"id": "fc-e3", "lo_level": "evaluate", "difficulty": "hard", "set": 1,
             "question": "A classmate says '1/3 is bigger than 1/2 because 3 is bigger than 2.' Is this correct? Answer Yes or No.",
             "answer": "No"},
            {"id": "fc-c1", "lo_level": "create", "difficulty": "hard", "set": 1,
             "question": "Complete this word problem so the answer is 1/4: 'A pizza is cut into 8 slices. ___ slices are pepperoni.' Fill in the blank with the correct number of slices.",
             "answer": "2"},
            {"id": "fc-c2", "lo_level": "create", "difficulty": "hard", "set": 1,
             "question": "Complete this multiplication word problem so it correctly represents 2/3 x 3/4: 'A garden is ___ full of flowers, and 3/4 of the flowered area is roses.' Fill in the missing fraction.",
             "answer": "2/3", "answer_type": "fraction"},
            {"id": "fc-c3", "lo_level": "create", "difficulty": "hard", "set": 1,
             "question": "Fill in the missing fraction to complete this addition word problem with answer 1: 'A tank is 1/3 full. You add ___ more to make it completely full.'",
             "answer": "2/3", "answer_type": "fraction"},
            # ---- Set 2 (retake quiz - different numbers, same structure) ----
            {"id": "fc-r1-2", "lo_level": "remember", "difficulty": "easy", "set": 2,
             "question": "In the fraction 5/9, what is the number 5 called?",
             "answer": "numerator"},
            {"id": "fc-r2-2", "lo_level": "remember", "difficulty": "easy", "set": 2,
             "question": "What is the reciprocal of 3/7?",
             "answer": "7/3", "answer_type": "fraction"},
            {"id": "fc-r3-2", "lo_level": "remember", "difficulty": "easy", "set": 2,
             "question": "When multiplying two fractions, you multiply the numerators together and multiply the ___ together. Fill in the blank.",
             "answer": "denominators", "accepted_answers": ["denominator"]},
            {"id": "fc-u1-2", "lo_level": "understand", "difficulty": "easy", "set": 2,
             "question": "Before subtracting fractions with different denominators, you must first find a common ___. Fill in the blank.",
             "answer": "denominator"},
            {"id": "fc-u2-2", "lo_level": "understand", "difficulty": "medium", "set": 2,
             "question": "Multiplying a number by a fraction less than 1 makes the result ___ (bigger or smaller)?",
             "answer": "smaller"},
            {"id": "fc-u3-2", "lo_level": "understand", "difficulty": "medium", "set": 2,
             "question": "10/15 simplifies to 2/3 because both 10 and 15 share a common factor of ___. Fill in the blank with a number.",
             "answer": "5"},
            {"id": "fc-a1-2", "lo_level": "apply", "difficulty": "medium", "set": 2,
             "question": "Simplify 14/21.",
             "answer": "2/3", "answer_type": "fraction"},
            {"id": "fc-a2-2", "lo_level": "apply", "difficulty": "medium", "set": 2,
             "question": "Evaluate: 2/7 x 3/4",
             "answer": "3/14", "answer_type": "fraction"},
            {"id": "fc-a3-2", "lo_level": "apply", "difficulty": "medium", "set": 2,
             "question": "Evaluate: 5/6 / (2/3)",
             "answer": "5/4", "answer_type": "fraction"},
            {"id": "fc-n1-2", "lo_level": "analyze", "difficulty": "medium", "set": 2,
             "question": "A recipe needs 7/8 cup butter. You've already added 1/2 cup. How much more do you need?",
             "answer": "3/8", "answer_type": "fraction"},
            {"id": "fc-n2-2", "lo_level": "analyze", "difficulty": "hard", "set": 2,
             "question": "You have 9/10 liter of paint. Each can holds 3/10 liter. How many FULL cans can you fill?",
             "answer": "3"},
            {"id": "fc-n3-2", "lo_level": "analyze", "difficulty": "medium", "set": 2,
             "question": "A classroom has 15 students. 9 are boys and the rest are girls. What fraction (simplified) of the class is girls?",
             "answer": "2/5", "answer_type": "fraction"},
            {"id": "fc-e1-2", "lo_level": "evaluate", "difficulty": "hard", "set": 2,
             "question": "Compare 7/10 and 2/3. Which is larger? Answer with the larger fraction.",
             "answer": "7/10", "answer_type": "fraction"},
            {"id": "fc-e2-2", "lo_level": "evaluate", "difficulty": "hard", "set": 2,
             "question": "By how much is 7/10 larger than 2/3? Give the simplest fraction.",
             "answer": "1/30", "answer_type": "fraction"},
            {"id": "fc-e3-2", "lo_level": "evaluate", "difficulty": "hard", "set": 2,
             "question": "A classmate says '3/4 is bigger than 4/5 because 3+4=7 is less than 4+5=9.' Is this correct? Answer Yes or No.",
             "answer": "No"},
            {"id": "fc-c1-2", "lo_level": "create", "difficulty": "hard", "set": 2,
             "question": "Complete this word problem so the answer is 3/5: 'A pizza is cut into 10 slices. ___ slices are mushroom.' Fill in the blank with the correct number of slices.",
             "answer": "6"},
            {"id": "fc-c2-2", "lo_level": "create", "difficulty": "hard", "set": 2,
             "question": "Complete this multiplication word problem so it correctly represents 3/4 x 2/5: 'A field is ___ full of corn, and 2/5 of the corn area is sweetcorn.' Fill in the missing fraction.",
             "answer": "3/4", "answer_type": "fraction"},
            {"id": "fc-c3-2", "lo_level": "create", "difficulty": "hard", "set": 2,
             "question": "Fill in the missing fraction to complete this addition word problem with answer 1: 'A jar is 2/5 full. You add ___ more to make it completely full.'",
             "answer": "3/5", "answer_type": "fraction"},
        ],
    },
}


def get_lesson(lesson_id):
    return LESSONS.get(lesson_id)


def list_lessons():
    return [
        {
            "lesson_id": lid,
            "title": l["title"],
            "subject": l["subject"],
            # Count for quiz_set 1 specifically (what a student actually
            # sees on their first attempt), not the full question bank -
            # pilot-format lessons have a second, equally-sized retake set
            # that would otherwise double this number.
            "question_count": sum(1 for q in l["questions"] if q.get("set", 1) == 1),
        }
        for lid, l in LESSONS.items()
    ]


def get_quiz_for_lesson(lesson_id, quiz_set=1):
    """Question (+ options, for legacy MCQ lessons) only - the answer key
    never goes to the client. Lessons not yet migrated to the free-text
    pilot format have no "set" field on their questions at all - treated as
    set 1 implicitly, so requesting quiz_set=2 against one of them falls
    back to returning its one and only set rather than an empty quiz."""
    lesson = get_lesson(lesson_id)
    if not lesson:
        return None

    questions = [q for q in lesson["questions"] if q.get("set", 1) == quiz_set]
    if not questions and quiz_set != 1:
        questions = [q for q in lesson["questions"] if q.get("set", 1) == 1]
        quiz_set = 1

    return {
        "lesson_id": lesson_id,
        "title": lesson["title"],
        "subject": lesson["subject"],
        "quiz_set": quiz_set,
        "questions": [
            {
                "id": q["id"], "lo_level": q["lo_level"], "difficulty": q["difficulty"],
                "question": q["question"],
                **({"options": q["options"]} if "options" in q else {}),
            }
            for q in questions
        ],
    }
