"""
lesson_resources.py — Real, lesson-specific learning resources for the
weak-LO recommendations shown after a real quiz submission (lessons.py +
mastery.py), replacing data.py's RESOURCES: those were generic Bloom-level
placeholders ("Concept Mapping Tutorial", "Evidence-Based Decision Making
Guide") reused for every lesson regardless of topic - not tied to any real
URL, and not actually about Python functions or photosynthesis specifically.

Every resource here is a search-query URL (YouTube or Google) rather than a
hand-picked video/article link - a specific video ID can go dead, be wrong,
or simply not exist; a search query is always valid and still points the
student at real, current, relevant results for that exact topic and
cognitive level.
"""

from __future__ import annotations
from urllib.parse import quote_plus


def _youtube_search(query: str) -> str:
    return f"https://www.youtube.com/results?search_query={quote_plus(query)}"


def _google_search(query: str) -> str:
    return f"https://www.google.com/search?q={quote_plus(query)}"


LESSON_RESOURCES: dict[str, dict[str, list[dict]]] = {
    "python-functions": {
        "remember": [
            {"id": "pf-r-1", "title": "Python Functions Basics, Explained", "type": "video", "difficulty": "easy",
             "url": _youtube_search("python functions basics explained for beginners")},
            {"id": "pf-r-2", "title": "Python Functions Cheat Sheet", "type": "reading", "difficulty": "easy",
             "url": _google_search("python functions cheat sheet definition syntax")},
            {"id": "pf-r-3", "title": "Python Functions Quiz for Beginners", "type": "quiz", "difficulty": "easy",
             "url": _google_search("python functions quiz beginner")},
        ],
        "understand": [
            {"id": "pf-u-1", "title": "Python Functions Explained Simply", "type": "reading", "difficulty": "easy",
             "url": _google_search("python functions explained simply for beginners")},
            {"id": "pf-u-2", "title": "Python Functions Tutorial (Video)", "type": "video", "difficulty": "easy",
             "url": _youtube_search("python functions tutorial for beginners")},
            {"id": "pf-u-3", "title": "Try It Yourself: Python Functions", "type": "interactive", "difficulty": "medium",
             "url": "https://www.w3schools.com/python/python_functions.asp"},
        ],
        "apply": [
            {"id": "pf-a-1", "title": "Python Functions Practice Walkthrough", "type": "video", "difficulty": "medium",
             "url": _youtube_search("python functions practice problems walkthrough")},
            {"id": "pf-a-2", "title": "Python Functions Practice Exercises", "type": "interactive", "difficulty": "medium",
             "url": _google_search("python functions practice exercises with solutions")},
            {"id": "pf-a-3", "title": "Real-World Python Function Examples", "type": "reading", "difficulty": "medium",
             "url": _google_search("python functions real world examples")},
        ],
        "analyze": [
            {"id": "pf-n-1", "title": "Default vs Mutable Arguments Explained", "type": "reading", "difficulty": "hard",
             "url": _google_search("python mutable default arguments gotcha explained")},
            {"id": "pf-n-2", "title": "Python Scope and Parameters (Video)", "type": "video", "difficulty": "medium",
             "url": _youtube_search("python function scope and parameters explained")},
            {"id": "pf-n-3", "title": "Python Functions - Advanced Quiz", "type": "quiz", "difficulty": "hard",
             "url": _google_search("python functions advanced quiz recursion args kwargs")},
        ],
        "evaluate": [
            {"id": "pf-e-1", "title": "Python Function Design Best Practices", "type": "reading", "difficulty": "hard",
             "url": _google_search("python function design best practices clean code")},
            {"id": "pf-e-2", "title": "Python Code Review: Functions (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("python function code review anti patterns")},
            {"id": "pf-e-3", "title": "Named Parameters vs **kwargs Debate", "type": "interactive", "difficulty": "hard",
             "url": _google_search("python named parameters vs kwargs pros and cons")},
        ],
        "create": [
            {"id": "pf-c-1", "title": "Beginner Python Project Ideas Using Functions", "type": "interactive", "difficulty": "hard",
             "url": _google_search("beginner python project ideas using functions")},
            {"id": "pf-c-2", "title": "Build a Python Decorator (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("build a python decorator from scratch tutorial")},
            {"id": "pf-c-3", "title": "Python Function Design Project Guide", "type": "reading", "difficulty": "hard",
             "url": _google_search("python function design project guide")},
        ],
    },
    "photosynthesis": {
        "remember": [
            {"id": "ph-r-1", "title": "Photosynthesis Basics, Explained", "type": "video", "difficulty": "easy",
             "url": _youtube_search("photosynthesis basics explained for students")},
            {"id": "ph-r-2", "title": "Photosynthesis: Key Terms & Definition", "type": "reading", "difficulty": "easy",
             "url": "https://en.wikipedia.org/wiki/Photosynthesis"},
            {"id": "ph-r-3", "title": "Photosynthesis Quiz (Grade 9)", "type": "quiz", "difficulty": "easy",
             "url": _google_search("photosynthesis quiz grade 9")},
        ],
        "understand": [
            {"id": "ph-u-1", "title": "Photosynthesis Explained Simply", "type": "reading", "difficulty": "easy",
             "url": _google_search("photosynthesis explained simply for students")},
            {"id": "ph-u-2", "title": "Photosynthesis Animation (Video)", "type": "video", "difficulty": "easy",
             "url": _youtube_search("photosynthesis explained animation for beginners")},
            {"id": "ph-u-3", "title": "Interactive Photosynthesis Diagram", "type": "interactive", "difficulty": "medium",
             "url": _google_search("photosynthesis interactive diagram labeled")},
        ],
        "apply": [
            {"id": "ph-a-1", "title": "Photosynthesis Experiment (Video)", "type": "video", "difficulty": "medium",
             "url": _youtube_search("photosynthesis experiment real world example")},
            {"id": "ph-a-2", "title": "Photosynthesis Practice Worksheet", "type": "interactive", "difficulty": "medium",
             "url": _google_search("photosynthesis practice problems worksheet")},
            {"id": "ph-a-3", "title": "Photosynthesis in Everyday Life", "type": "reading", "difficulty": "medium",
             "url": _google_search("photosynthesis real world applications everyday life")},
        ],
        "analyze": [
            {"id": "ph-n-1", "title": "Photosynthesis vs Cellular Respiration", "type": "reading", "difficulty": "hard",
             "url": _google_search("photosynthesis vs cellular respiration comparison")},
            {"id": "ph-n-2", "title": "What Affects Photosynthesis Rate? (Video)", "type": "video", "difficulty": "medium",
             "url": _youtube_search("factors affecting rate of photosynthesis explained")},
            {"id": "ph-n-3", "title": "Photosynthesis Analysis Quiz", "type": "quiz", "difficulty": "hard",
             "url": _google_search("photosynthesis analysis quiz advanced grade 9")},
        ],
        "evaluate": [
            {"id": "ph-e-1", "title": "Design a Photosynthesis Experiment", "type": "reading", "difficulty": "hard",
             "url": _google_search("how to design a photosynthesis experiment variables")},
            {"id": "ph-e-2", "title": "Photosynthesis Critical Thinking (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("photosynthesis critical thinking questions explained")},
            {"id": "ph-e-3", "title": "Evaluate a Photosynthesis Case Study", "type": "interactive", "difficulty": "hard",
             "url": _google_search("photosynthesis case study evaluation questions")},
        ],
        "create": [
            {"id": "ph-c-1", "title": "Photosynthesis Science Fair Ideas", "type": "interactive", "difficulty": "hard",
             "url": _google_search("photosynthesis science fair project ideas")},
            {"id": "ph-c-2", "title": "Build Your Own Photosynthesis Model (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("build a photosynthesis model project")},
            {"id": "ph-c-3", "title": "Photosynthesis Project Guide", "type": "reading", "difficulty": "hard",
             "url": _google_search("photosynthesis project guide for students")},
        ],
    },
    "fractions-bodmas": {
        "remember": [
            {"id": "fr-r-1", "title": "BODMAS Explained, Step by Step", "type": "video", "difficulty": "easy",
             "url": _youtube_search("BODMAS order of operations explained for grade 9")},
            {"id": "fr-r-2", "title": "BODMAS Rules Cheat Sheet", "type": "reading", "difficulty": "easy",
             "url": _google_search("BODMAS order of operations rules cheat sheet")},
            {"id": "fr-r-3", "title": "BODMAS Quiz for Beginners", "type": "quiz", "difficulty": "easy",
             "url": _google_search("BODMAS order of operations quiz grade 9")},
        ],
        "understand": [
            {"id": "fr-u-1", "title": "Why Order of Operations Matters", "type": "reading", "difficulty": "easy",
             "url": _google_search("why order of operations BODMAS matters explained")},
            {"id": "fr-u-2", "title": "Adding Fractions with Different Denominators (Video)", "type": "video", "difficulty": "easy",
             "url": _youtube_search("adding fractions with different denominators explained")},
            {"id": "fr-u-3", "title": "Try It Yourself: Fraction Addition", "type": "interactive", "difficulty": "medium",
             "url": "https://www.mathsisfun.com/fractions_addition.html"},
        ],
        "apply": [
            {"id": "fr-a-1", "title": "BODMAS Practice Problems Walkthrough", "type": "video", "difficulty": "medium",
             "url": _youtube_search("BODMAS practice problems walkthrough grade 9")},
            {"id": "fr-a-2", "title": "Fraction and BODMAS Practice Exercises", "type": "interactive", "difficulty": "medium",
             "url": _google_search("BODMAS fractions practice exercises with solutions")},
            {"id": "fr-a-3", "title": "Real-World BODMAS Examples", "type": "reading", "difficulty": "medium",
             "url": _google_search("BODMAS real world word problems examples")},
        ],
        "analyze": [
            {"id": "fr-n-1", "title": "Common BODMAS Mistakes Explained", "type": "reading", "difficulty": "hard",
             "url": _google_search("common BODMAS order of operations mistakes explained")},
            {"id": "fr-n-2", "title": "Multiplication vs Division Order (Video)", "type": "video", "difficulty": "medium",
             "url": _youtube_search("BODMAS multiplication division left to right explained")},
            {"id": "fr-n-3", "title": "BODMAS Advanced Quiz", "type": "quiz", "difficulty": "hard",
             "url": _google_search("BODMAS advanced quiz mixed fractions brackets")},
        ],
        "evaluate": [
            {"id": "fr-e-1", "title": "Debunking BODMAS Misconceptions", "type": "reading", "difficulty": "hard",
             "url": _google_search("BODMAS misconceptions debunked division multiplication")},
            {"id": "fr-e-2", "title": "BODMAS Critical Thinking Questions (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("BODMAS critical thinking tricky questions explained")},
            {"id": "fr-e-3", "title": "Evaluate BODMAS Problem Solutions", "type": "interactive", "difficulty": "hard",
             "url": _google_search("BODMAS evaluate correct solution word problems")},
        ],
        "create": [
            {"id": "fr-c-1", "title": "Design Your Own BODMAS Word Problem", "type": "interactive", "difficulty": "hard",
             "url": _google_search("how to write a BODMAS fraction word problem")},
            {"id": "fr-c-2", "title": "BODMAS Word Problem Design (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("creating BODMAS word problems tutorial")},
            {"id": "fr-c-3", "title": "BODMAS Project Guide", "type": "reading", "difficulty": "hard",
             "url": _google_search("BODMAS fractions project guide for students")},
        ],
    },
    "pythagorean-theorem": {
        "remember": [
            {"id": "pt-r-1", "title": "Pythagorean Theorem Basics, Explained", "type": "video", "difficulty": "easy",
             "url": _youtube_search("Pythagorean theorem basics explained for beginners")},
            {"id": "pt-r-2", "title": "Pythagorean Theorem Cheat Sheet", "type": "reading", "difficulty": "easy",
             "url": _google_search("Pythagorean theorem formula cheat sheet")},
            {"id": "pt-r-3", "title": "Pythagorean Theorem Quiz for Beginners", "type": "quiz", "difficulty": "easy",
             "url": _google_search("Pythagorean theorem quiz grade 9")},
        ],
        "understand": [
            {"id": "pt-u-1", "title": "Why the Pythagorean Theorem Works", "type": "reading", "difficulty": "easy",
             "url": _google_search("why does the Pythagorean theorem work proof explained simply")},
            {"id": "pt-u-2", "title": "Pythagorean Theorem Visual Proof (Video)", "type": "video", "difficulty": "easy",
             "url": _youtube_search("Pythagorean theorem visual proof animation")},
            {"id": "pt-u-3", "title": "Try It Yourself: Right Triangles", "type": "interactive", "difficulty": "medium",
             "url": "https://www.mathsisfun.com/pythagoras.html"},
        ],
        "apply": [
            {"id": "pt-a-1", "title": "Pythagorean Theorem Practice Walkthrough", "type": "video", "difficulty": "medium",
             "url": _youtube_search("Pythagorean theorem practice problems walkthrough")},
            {"id": "pt-a-2", "title": "Pythagorean Theorem Practice Exercises", "type": "interactive", "difficulty": "medium",
             "url": _google_search("Pythagorean theorem practice exercises with solutions")},
            {"id": "pt-a-3", "title": "Real-World Pythagorean Theorem Examples", "type": "reading", "difficulty": "medium",
             "url": _google_search("Pythagorean theorem real world applications examples")},
        ],
        "analyze": [
            {"id": "pt-n-1", "title": "Common Pythagorean Theorem Mistakes", "type": "reading", "difficulty": "hard",
             "url": _google_search("common Pythagorean theorem mistakes explained")},
            {"id": "pt-n-2", "title": "Identifying Right Triangles (Video)", "type": "video", "difficulty": "medium",
             "url": _youtube_search("how to tell if a triangle is a right triangle Pythagorean")},
            {"id": "pt-n-3", "title": "Pythagorean Theorem Advanced Quiz", "type": "quiz", "difficulty": "hard",
             "url": _google_search("Pythagorean theorem advanced quiz word problems")},
        ],
        "evaluate": [
            {"id": "pt-e-1", "title": "When the Pythagorean Theorem Doesn't Apply", "type": "reading", "difficulty": "hard",
             "url": _google_search("Pythagorean theorem limitations non right triangles Law of Cosines")},
            {"id": "pt-e-2", "title": "Pythagorean Theorem Critical Thinking (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("Pythagorean theorem critical thinking tricky questions")},
            {"id": "pt-e-3", "title": "Evaluate Pythagorean Theorem Claims", "type": "interactive", "difficulty": "hard",
             "url": _google_search("Pythagorean theorem true or false evaluate claims")},
        ],
        "create": [
            {"id": "pt-c-1", "title": "Design a Pythagorean Theorem Word Problem", "type": "interactive", "difficulty": "hard",
             "url": _google_search("how to write a Pythagorean theorem word problem")},
            {"id": "pt-c-2", "title": "Pythagorean Theorem Project Ideas (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("Pythagorean theorem project ideas for students")},
            {"id": "pt-c-3", "title": "Pythagorean Theorem Project Guide", "type": "reading", "difficulty": "hard",
             "url": _google_search("Pythagorean theorem project guide real world design")},
        ],
    },
    "linear-equations": {
        "remember": [
            {"id": "le-r-1", "title": "Solving Linear Equations Basics", "type": "video", "difficulty": "easy",
             "url": _youtube_search("solving linear equations basics explained for beginners")},
            {"id": "le-r-2", "title": "Linear Equations Cheat Sheet", "type": "reading", "difficulty": "easy",
             "url": _google_search("solving linear equations cheat sheet steps")},
            {"id": "le-r-3", "title": "Linear Equations Quiz for Beginners", "type": "quiz", "difficulty": "easy",
             "url": _google_search("solving linear equations quiz grade 9")},
        ],
        "understand": [
            {"id": "le-u-1", "title": "Why We Balance Both Sides of an Equation", "type": "reading", "difficulty": "easy",
             "url": _google_search("why keep an equation balanced both sides explained")},
            {"id": "le-u-2", "title": "Linear Equations Explained Simply (Video)", "type": "video", "difficulty": "easy",
             "url": _youtube_search("linear equations explained simply for beginners")},
            {"id": "le-u-3", "title": "Try It Yourself: Solving Equations", "type": "interactive", "difficulty": "medium",
             "url": "https://www.mathsisfun.com/algebra/linear-equations.html"},
        ],
        "apply": [
            {"id": "le-a-1", "title": "Linear Equations Practice Walkthrough", "type": "video", "difficulty": "medium",
             "url": _youtube_search("solving linear equations practice problems walkthrough")},
            {"id": "le-a-2", "title": "Linear Equations Practice Exercises", "type": "interactive", "difficulty": "medium",
             "url": _google_search("linear equations practice exercises with solutions")},
            {"id": "le-a-3", "title": "Real-World Linear Equation Examples", "type": "reading", "difficulty": "medium",
             "url": _google_search("linear equations real world word problems examples")},
        ],
        "analyze": [
            {"id": "le-n-1", "title": "Common Equation-Solving Mistakes", "type": "reading", "difficulty": "hard",
             "url": _google_search("common linear equation solving mistakes explained")},
            {"id": "le-n-2", "title": "Equations with Variables on Both Sides (Video)", "type": "video", "difficulty": "medium",
             "url": _youtube_search("linear equations variables both sides explained")},
            {"id": "le-n-3", "title": "Linear Equations Advanced Quiz", "type": "quiz", "difficulty": "hard",
             "url": _google_search("linear equations advanced quiz word problems")},
        ],
        "evaluate": [
            {"id": "le-e-1", "title": "Guess-and-Check vs Algebraic Methods", "type": "reading", "difficulty": "hard",
             "url": _google_search("guess and check vs algebra solving equations efficiency")},
            {"id": "le-e-2", "title": "Linear Equations Critical Thinking (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("linear equations critical thinking tricky questions")},
            {"id": "le-e-3", "title": "Evaluate Equation-Solving Strategies", "type": "interactive", "difficulty": "hard",
             "url": _google_search("evaluate different strategies for solving linear equations")},
        ],
        "create": [
            {"id": "le-c-1", "title": "Design Your Own Linear Equation Word Problem", "type": "interactive", "difficulty": "hard",
             "url": _google_search("how to write a linear equation word problem")},
            {"id": "le-c-2", "title": "Linear Equation Word Problem Design (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("creating linear equation word problems tutorial")},
            {"id": "le-c-3", "title": "Linear Equations Project Guide", "type": "reading", "difficulty": "hard",
             "url": _google_search("linear equations project guide for students")},
        ],
    },
    "algebraic-fractions": {
        "remember": [
            {"id": "af-r-1", "title": "Algebraic Fractions Basics, Explained", "type": "video", "difficulty": "easy",
             "url": _youtube_search("algebraic fractions basics explained for beginners")},
            {"id": "af-r-2", "title": "Algebraic Fractions Cheat Sheet", "type": "reading", "difficulty": "easy",
             "url": _google_search("algebraic fractions cheat sheet simplifying rules")},
            {"id": "af-r-3", "title": "Algebraic Fractions Quiz for Beginners", "type": "quiz", "difficulty": "easy",
             "url": _google_search("algebraic fractions quiz grade 9")},
        ],
        "understand": [
            {"id": "af-u-1", "title": "Why Denominators Can't Be Zero", "type": "reading", "difficulty": "easy",
             "url": _google_search("why can't the denominator be zero explained")},
            {"id": "af-u-2", "title": "Simplifying Algebraic Fractions (Video)", "type": "video", "difficulty": "easy",
             "url": _youtube_search("simplifying algebraic fractions explained for beginners")},
            {"id": "af-u-3", "title": "Try It Yourself: Algebraic Fractions", "type": "interactive", "difficulty": "medium",
             "url": _google_search("algebraic fractions interactive practice simplify")},
        ],
        "apply": [
            {"id": "af-a-1", "title": "Algebraic Fractions Practice Walkthrough", "type": "video", "difficulty": "medium",
             "url": _youtube_search("simplifying algebraic fractions practice walkthrough")},
            {"id": "af-a-2", "title": "Algebraic Fractions Practice Exercises", "type": "interactive", "difficulty": "medium",
             "url": _google_search("algebraic fractions practice exercises with solutions")},
            {"id": "af-a-3", "title": "Factoring Before Simplifying, Explained", "type": "reading", "difficulty": "medium",
             "url": _google_search("factoring algebraic fractions before simplifying explained")},
        ],
        "analyze": [
            {"id": "af-n-1", "title": "Common Algebraic Fraction Mistakes", "type": "reading", "difficulty": "hard",
             "url": _google_search("common algebraic fraction simplifying mistakes explained")},
            {"id": "af-n-2", "title": "Cancelling Terms vs Factors (Video)", "type": "video", "difficulty": "medium",
             "url": _youtube_search("algebraic fractions cancelling terms vs factors mistake")},
            {"id": "af-n-3", "title": "Algebraic Fractions Advanced Quiz", "type": "quiz", "difficulty": "hard",
             "url": _google_search("algebraic fractions advanced quiz factoring simplify")},
        ],
        "evaluate": [
            {"id": "af-e-1", "title": "When Can You Really Cancel a Term?", "type": "reading", "difficulty": "hard",
             "url": _google_search("when can you cancel terms in algebraic fractions rules")},
            {"id": "af-e-2", "title": "Algebraic Fractions Critical Thinking (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("algebraic fractions critical thinking tricky questions")},
            {"id": "af-e-3", "title": "Evaluate Algebraic Fraction Simplifications", "type": "interactive", "difficulty": "hard",
             "url": _google_search("evaluate correct algebraic fraction simplification examples")},
        ],
        "create": [
            {"id": "af-c-1", "title": "Design Your Own Algebraic Fraction Problem", "type": "interactive", "difficulty": "hard",
             "url": _google_search("how to write an algebraic fraction simplification problem")},
            {"id": "af-c-2", "title": "Algebraic Fraction Problem Design (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("creating algebraic fraction problems tutorial")},
            {"id": "af-c-3", "title": "Algebraic Fractions Project Guide", "type": "reading", "difficulty": "hard",
             "url": _google_search("algebraic fractions project guide for students")},
        ],
    },
    "volume-capacity": {
        "remember": [
            {"id": "vc-r-1", "title": "Volume of a Cuboid, Explained", "type": "video", "difficulty": "easy",
             "url": _youtube_search("volume of a cuboid explained for beginners")},
            {"id": "vc-r-2", "title": "Volume and Capacity Cheat Sheet", "type": "reading", "difficulty": "easy",
             "url": _google_search("volume capacity formula cheat sheet cm3 litres")},
            {"id": "vc-r-3", "title": "Volume and Capacity Quiz for Beginners", "type": "quiz", "difficulty": "easy",
             "url": _google_search("volume and capacity quiz grade 9")},
        ],
        "understand": [
            {"id": "vc-u-1", "title": "Why Volume Uses Cubic Units", "type": "reading", "difficulty": "easy",
             "url": _google_search("why is volume measured in cubic units explained")},
            {"id": "vc-u-2", "title": "Converting cm3 to Litres (Video)", "type": "video", "difficulty": "easy",
             "url": _youtube_search("converting cubic centimetres to litres explained")},
            {"id": "vc-u-3", "title": "Try It Yourself: Volume Calculator", "type": "interactive", "difficulty": "medium",
             "url": "https://www.mathsisfun.com/geometry/volume.html"},
        ],
        "apply": [
            {"id": "vc-a-1", "title": "Volume and Capacity Practice Walkthrough", "type": "video", "difficulty": "medium",
             "url": _youtube_search("volume capacity practice problems walkthrough")},
            {"id": "vc-a-2", "title": "Volume and Capacity Practice Exercises", "type": "interactive", "difficulty": "medium",
             "url": _google_search("volume capacity practice exercises with solutions")},
            {"id": "vc-a-3", "title": "Real-World Volume and Capacity Examples", "type": "reading", "difficulty": "medium",
             "url": _google_search("volume capacity real world examples fish tank aquarium")},
        ],
        "analyze": [
            {"id": "vc-n-1", "title": "Common Volume Calculation Mistakes", "type": "reading", "difficulty": "hard",
             "url": _google_search("common volume calculation mistakes cm3 litres explained")},
            {"id": "vc-n-2", "title": "Same Volume, Different Shapes (Video)", "type": "video", "difficulty": "medium",
             "url": _youtube_search("same volume different dimensions shapes explained")},
            {"id": "vc-n-3", "title": "Volume and Capacity Advanced Quiz", "type": "quiz", "difficulty": "hard",
             "url": _google_search("volume capacity advanced quiz word problems")},
        ],
        "evaluate": [
            {"id": "vc-e-1", "title": "Checking Advertised Capacity Claims", "type": "reading", "difficulty": "hard",
             "url": _google_search("how to check advertised tank capacity claims volume")},
            {"id": "vc-e-2", "title": "Volume and Capacity Critical Thinking (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("volume capacity critical thinking tricky questions")},
            {"id": "vc-e-3", "title": "Evaluate Volume Calculation Claims", "type": "interactive", "difficulty": "hard",
             "url": _google_search("evaluate true or false volume calculation claims")},
        ],
        "create": [
            {"id": "vc-c-1", "title": "Design Your Own Volume Word Problem", "type": "interactive", "difficulty": "hard",
             "url": _google_search("how to write a volume capacity word problem")},
            {"id": "vc-c-2", "title": "Volume Word Problem Design (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("creating volume capacity word problems tutorial")},
            {"id": "vc-c-3", "title": "Volume and Capacity Project Guide", "type": "reading", "difficulty": "hard",
             "url": _google_search("volume capacity project guide for students")},
        ],
    },
    "number-patterns": {
        "remember": [
            {"id": "np-r-1", "title": "Number Patterns Basics, Explained", "type": "video", "difficulty": "easy",
             "url": _youtube_search("number patterns sequences basics explained for beginners")},
            {"id": "np-r-2", "title": "Number Patterns Cheat Sheet", "type": "reading", "difficulty": "easy",
             "url": _google_search("number patterns general term Tn cheat sheet")},
            {"id": "np-r-3", "title": "Number Patterns Quiz for Beginners", "type": "quiz", "difficulty": "easy",
             "url": _google_search("number patterns sequences quiz grade 9")},
        ],
        "understand": [
            {"id": "np-u-1", "title": "Why the General Term Formula Works", "type": "reading", "difficulty": "easy",
             "url": _google_search("why general term formula Tn works explained")},
            {"id": "np-u-2", "title": "Finding the Common Difference (Video)", "type": "video", "difficulty": "easy",
             "url": _youtube_search("finding common difference arithmetic sequence explained")},
            {"id": "np-u-3", "title": "Try It Yourself: Number Sequences", "type": "interactive", "difficulty": "medium",
             "url": "https://www.mathsisfun.com/algebra/sequences-finding-rule.html"},
        ],
        "apply": [
            {"id": "np-a-1", "title": "Number Patterns Practice Walkthrough", "type": "video", "difficulty": "medium",
             "url": _youtube_search("number patterns general term practice walkthrough")},
            {"id": "np-a-2", "title": "Number Patterns Practice Exercises", "type": "interactive", "difficulty": "medium",
             "url": _google_search("number patterns practice exercises with solutions")},
            {"id": "np-a-3", "title": "Real-World Number Pattern Examples", "type": "reading", "difficulty": "medium",
             "url": _google_search("number patterns real world examples applications")},
        ],
        "analyze": [
            {"id": "np-n-1", "title": "Arithmetic vs Quadratic Patterns", "type": "reading", "difficulty": "hard",
             "url": _google_search("arithmetic sequence vs quadratic number pattern difference")},
            {"id": "np-n-2", "title": "Spotting Non-Arithmetic Sequences (Video)", "type": "video", "difficulty": "medium",
             "url": _youtube_search("identifying non arithmetic number sequences explained")},
            {"id": "np-n-3", "title": "Number Patterns Advanced Quiz", "type": "quiz", "difficulty": "hard",
             "url": _google_search("number patterns advanced quiz general term")},
        ],
        "evaluate": [
            {"id": "np-e-1", "title": "Why One Pattern Can Have Many Rules", "type": "reading", "difficulty": "hard",
             "url": _google_search("multiple rules fit same number sequence ambiguity")},
            {"id": "np-e-2", "title": "Number Patterns Critical Thinking (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("number patterns critical thinking tricky questions")},
            {"id": "np-e-3", "title": "Evaluate Number Pattern Claims", "type": "interactive", "difficulty": "hard",
             "url": _google_search("evaluate true or false number pattern claims")},
        ],
        "create": [
            {"id": "np-c-1", "title": "Design Your Own Number Pattern Puzzle", "type": "interactive", "difficulty": "hard",
             "url": _google_search("how to create a number pattern sequence puzzle")},
            {"id": "np-c-2", "title": "Number Pattern Puzzle Design (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("creating number pattern puzzles tutorial")},
            {"id": "np-c-3", "title": "Number Patterns Project Guide", "type": "reading", "difficulty": "hard",
             "url": _google_search("number patterns project guide for students")},
        ],
    },
    "area-of-shapes": {
        "remember": [
            {"id": "ar-r-1", "title": "Area of Squares, Rectangles & Triangles", "type": "video", "difficulty": "easy",
             "url": _youtube_search("area of square rectangle triangle explained for beginners")},
            {"id": "ar-r-2", "title": "Area Formulas Cheat Sheet", "type": "reading", "difficulty": "easy",
             "url": _google_search("area formulas cheat sheet square rectangle triangle")},
            {"id": "ar-r-3", "title": "Area of Shapes Quiz for Beginners", "type": "quiz", "difficulty": "easy",
             "url": _google_search("area of shapes quiz grade 9")},
        ],
        "understand": [
            {"id": "ar-u-1", "title": "Why Triangle Area Is Half Base Times Height", "type": "reading", "difficulty": "easy",
             "url": _google_search("why is triangle area half base times height explained")},
            {"id": "ar-u-2", "title": "Area of Shapes Explained Simply (Video)", "type": "video", "difficulty": "easy",
             "url": _youtube_search("area of shapes explained simply for beginners")},
            {"id": "ar-u-3", "title": "Try It Yourself: Area Calculator", "type": "interactive", "difficulty": "medium",
             "url": "https://www.mathsisfun.com/area.html"},
        ],
        "apply": [
            {"id": "ar-a-1", "title": "Area of Shapes Practice Walkthrough", "type": "video", "difficulty": "medium",
             "url": _youtube_search("area of shapes practice problems walkthrough")},
            {"id": "ar-a-2", "title": "Area of Shapes Practice Exercises", "type": "interactive", "difficulty": "medium",
             "url": _google_search("area of shapes practice exercises with solutions")},
            {"id": "ar-a-3", "title": "Real-World Area Calculation Examples", "type": "reading", "difficulty": "medium",
             "url": _google_search("area calculation real world examples land plots")},
        ],
        "analyze": [
            {"id": "ar-n-1", "title": "Common Area Formula Mistakes", "type": "reading", "difficulty": "hard",
             "url": _google_search("common area formula mistakes triangle rectangle explained")},
            {"id": "ar-n-2", "title": "Same Area, Different Shapes (Video)", "type": "video", "difficulty": "medium",
             "url": _youtube_search("same area different shape dimensions explained")},
            {"id": "ar-n-3", "title": "Area of Shapes Advanced Quiz", "type": "quiz", "difficulty": "hard",
             "url": _google_search("area of shapes advanced quiz word problems")},
        ],
        "evaluate": [
            {"id": "ar-e-1", "title": "Evaluating Land Plot Area Claims", "type": "reading", "difficulty": "hard",
             "url": _google_search("how to verify advertised land plot area claims")},
            {"id": "ar-e-2", "title": "Area of Shapes Critical Thinking (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("area of shapes critical thinking tricky questions")},
            {"id": "ar-e-3", "title": "Evaluate Area Calculation Claims", "type": "interactive", "difficulty": "hard",
             "url": _google_search("evaluate true or false area calculation claims")},
        ],
        "create": [
            {"id": "ar-c-1", "title": "Design Your Own Area Word Problem", "type": "interactive", "difficulty": "hard",
             "url": _google_search("how to write an area of shapes word problem")},
            {"id": "ar-c-2", "title": "Area Word Problem Design (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("creating area of shapes word problems tutorial")},
            {"id": "ar-c-3", "title": "Area of Shapes Project Guide", "type": "reading", "difficulty": "hard",
             "url": _google_search("area of shapes project guide for students")},
        ],
    },
    "triangle-angle-theorems": {
        "remember": [
            {"id": "ta-r-1", "title": "Triangle Angle Sum Theorem, Explained", "type": "video", "difficulty": "easy",
             "url": _youtube_search("triangle angle sum theorem explained for beginners")},
            {"id": "ta-r-2", "title": "Triangle Angle Theorems Cheat Sheet", "type": "reading", "difficulty": "easy",
             "url": _google_search("triangle angle sum exterior angle theorem cheat sheet")},
            {"id": "ta-r-3", "title": "Triangle Angle Theorems Quiz for Beginners", "type": "quiz", "difficulty": "easy",
             "url": _google_search("triangle angle theorems quiz grade 9")},
        ],
        "understand": [
            {"id": "ta-u-1", "title": "Why Triangle Angles Sum to 180 Degrees", "type": "reading", "difficulty": "easy",
             "url": _google_search("why do triangle angles add up to 180 degrees proof")},
            {"id": "ta-u-2", "title": "Exterior Angle Theorem Explained (Video)", "type": "video", "difficulty": "easy",
             "url": _youtube_search("exterior angle theorem explained for beginners")},
            {"id": "ta-u-3", "title": "Try It Yourself: Triangle Angles", "type": "interactive", "difficulty": "medium",
             "url": "https://www.mathsisfun.com/angle-sum-of-a-triangle.html"},
        ],
        "apply": [
            {"id": "ta-a-1", "title": "Triangle Angle Theorems Practice Walkthrough", "type": "video", "difficulty": "medium",
             "url": _youtube_search("triangle angle sum exterior angle practice walkthrough")},
            {"id": "ta-a-2", "title": "Triangle Angle Practice Exercises", "type": "interactive", "difficulty": "medium",
             "url": _google_search("triangle angle theorems practice exercises with solutions")},
            {"id": "ta-a-3", "title": "Real-World Triangle Angle Examples", "type": "reading", "difficulty": "medium",
             "url": _google_search("triangle angle theorems real world examples surveying")},
        ],
        "analyze": [
            {"id": "ta-n-1", "title": "Common Triangle Angle Mistakes", "type": "reading", "difficulty": "hard",
             "url": _google_search("common triangle angle theorem mistakes explained")},
            {"id": "ta-n-2", "title": "Interior vs Exterior Angles (Video)", "type": "video", "difficulty": "medium",
             "url": _youtube_search("interior vs exterior angle triangle difference explained")},
            {"id": "ta-n-3", "title": "Triangle Angle Theorems Advanced Quiz", "type": "quiz", "difficulty": "hard",
             "url": _google_search("triangle angle theorems advanced quiz mixed problems")},
        ],
        "evaluate": [
            {"id": "ta-e-1", "title": "Is the Exterior Angle Theorem Enough on Its Own?", "type": "reading", "difficulty": "hard",
             "url": _google_search("exterior angle theorem vs angle sum theorem when to use")},
            {"id": "ta-e-2", "title": "Triangle Angle Critical Thinking (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("triangle angle theorems critical thinking tricky questions")},
            {"id": "ta-e-3", "title": "Evaluate Triangle Angle Claims", "type": "interactive", "difficulty": "hard",
             "url": _google_search("evaluate true or false triangle angle theorem claims")},
        ],
        "create": [
            {"id": "ta-c-1", "title": "Design Your Own Triangle Angle Problem", "type": "interactive", "difficulty": "hard",
             "url": _google_search("how to write a triangle angle theorem word problem")},
            {"id": "ta-c-2", "title": "Triangle Angle Problem Design (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("creating triangle angle word problems tutorial")},
            {"id": "ta-c-3", "title": "Triangle Angle Theorems Project Guide", "type": "reading", "difficulty": "hard",
             "url": _google_search("triangle angle theorems project guide for students")},
        ],
    },
    "algebraic-expressions": {
        "remember": [
            {"id": "ae-r-1", "title": "Algebraic Expressions Basics, Explained", "type": "video", "difficulty": "easy",
             "url": _youtube_search("algebraic expressions basics explained for beginners")},
            {"id": "ae-r-2", "title": "Algebraic Expressions Cheat Sheet", "type": "reading", "difficulty": "easy",
             "url": _google_search("algebraic expressions like terms cheat sheet")},
            {"id": "ae-r-3", "title": "Algebraic Expressions Quiz for Beginners", "type": "quiz", "difficulty": "easy",
             "url": _google_search("algebraic expressions quiz grade 9")},
        ],
        "understand": [
            {"id": "ae-u-1", "title": "Why Only Like Terms Combine", "type": "reading", "difficulty": "easy",
             "url": _google_search("why can you only combine like terms algebra explained")},
            {"id": "ae-u-2", "title": "The Distributive Law Explained (Video)", "type": "video", "difficulty": "easy",
             "url": _youtube_search("distributive law algebra explained for beginners")},
            {"id": "ae-u-3", "title": "Try It Yourself: Simplifying Expressions", "type": "interactive", "difficulty": "medium",
             "url": "https://www.mathsisfun.com/algebra/simplify.html"},
        ],
        "apply": [
            {"id": "ae-a-1", "title": "Algebraic Expressions Practice Walkthrough", "type": "video", "difficulty": "medium",
             "url": _youtube_search("simplifying algebraic expressions practice walkthrough")},
            {"id": "ae-a-2", "title": "Factorizing Quadratics Practice Exercises", "type": "interactive", "difficulty": "medium",
             "url": _google_search("factorizing quadratic expressions practice exercises with solutions")},
            {"id": "ae-a-3", "title": "Real-World Algebraic Expression Examples", "type": "reading", "difficulty": "medium",
             "url": _google_search("algebraic expressions real world word problems examples")},
        ],
        "analyze": [
            {"id": "ae-n-1", "title": "Common Factorizing Mistakes", "type": "reading", "difficulty": "hard",
             "url": _google_search("common factorizing quadratic expression mistakes explained")},
            {"id": "ae-n-2", "title": "Checking a Factorization by Expanding (Video)", "type": "video", "difficulty": "medium",
             "url": _youtube_search("check factoring by expanding brackets explained")},
            {"id": "ae-n-3", "title": "Algebraic Expressions Advanced Quiz", "type": "quiz", "difficulty": "hard",
             "url": _google_search("algebraic expressions advanced quiz factorizing substitution")},
        ],
        "evaluate": [
            {"id": "ae-e-1", "title": "Order of Operations in Substitution", "type": "reading", "difficulty": "hard",
             "url": _google_search("order of operations when substituting into algebraic expressions")},
            {"id": "ae-e-2", "title": "Algebraic Expressions Critical Thinking (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("algebraic expressions critical thinking tricky questions")},
            {"id": "ae-e-3", "title": "Evaluate Factorization Claims", "type": "interactive", "difficulty": "hard",
             "url": _google_search("evaluate correct factorization of quadratic expressions")},
        ],
        "create": [
            {"id": "ae-c-1", "title": "Design Your Own Algebraic Word Problem", "type": "interactive", "difficulty": "hard",
             "url": _google_search("how to write an algebraic expression substitution word problem")},
            {"id": "ae-c-2", "title": "Algebraic Word Problem Design (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("creating algebraic expression word problems tutorial")},
            {"id": "ae-c-3", "title": "Algebraic Expressions Project Guide", "type": "reading", "difficulty": "hard",
             "url": _google_search("algebraic expressions project guide for students")},
        ],
    },
    "rounding-off": {
        "remember": [
            {"id": "ro-r-1", "title": "Rounding Numbers Basics, Explained", "type": "video", "difficulty": "easy",
             "url": _youtube_search("rounding numbers basics explained for beginners")},
            {"id": "ro-r-2", "title": "Rounding Rules Cheat Sheet", "type": "reading", "difficulty": "easy",
             "url": _google_search("rounding numbers rules cheat sheet nearest 10 100")},
            {"id": "ro-r-3", "title": "Rounding Numbers Quiz for Beginners", "type": "quiz", "difficulty": "easy",
             "url": _google_search("rounding numbers quiz grade 9")},
        ],
        "understand": [
            {"id": "ro-u-1", "title": "Why We Round Numbers", "type": "reading", "difficulty": "easy",
             "url": _google_search("why do we round numbers estimation explained")},
            {"id": "ro-u-2", "title": "Significant Figures Explained (Video)", "type": "video", "difficulty": "easy",
             "url": _youtube_search("significant figures explained for beginners")},
            {"id": "ro-u-3", "title": "Try It Yourself: Rounding Calculator", "type": "interactive", "difficulty": "medium",
             "url": "https://www.mathsisfun.com/rounding-numbers.html"},
        ],
        "apply": [
            {"id": "ro-a-1", "title": "Rounding Practice Walkthrough", "type": "video", "difficulty": "medium",
             "url": _youtube_search("rounding numbers practice problems walkthrough")},
            {"id": "ro-a-2", "title": "Significant Figures Practice Exercises", "type": "interactive", "difficulty": "medium",
             "url": _google_search("significant figures practice exercises with solutions")},
            {"id": "ro-a-3", "title": "Real-World Rounding Examples", "type": "reading", "difficulty": "medium",
             "url": _google_search("rounding numbers real world examples estimation")},
        ],
        "analyze": [
            {"id": "ro-n-1", "title": "Common Rounding Mistakes", "type": "reading", "difficulty": "hard",
             "url": _google_search("common rounding numbers mistakes explained")},
            {"id": "ro-n-2", "title": "Leading Zeros and Significant Figures (Video)", "type": "video", "difficulty": "medium",
             "url": _youtube_search("leading zeros significant figures explained")},
            {"id": "ro-n-3", "title": "Rounding Advanced Quiz", "type": "quiz", "difficulty": "hard",
             "url": _google_search("rounding significant figures advanced quiz")},
        ],
        "evaluate": [
            {"id": "ro-e-1", "title": "When Rounding Up Isn't Fair", "type": "reading", "difficulty": "hard",
             "url": _google_search("problems with always rounding up estimates bias")},
            {"id": "ro-e-2", "title": "Rounding Critical Thinking (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("rounding numbers critical thinking tricky questions")},
            {"id": "ro-e-3", "title": "Evaluate Rounding Claims", "type": "interactive", "difficulty": "hard",
             "url": _google_search("evaluate true or false rounding numbers claims")},
        ],
        "create": [
            {"id": "ro-c-1", "title": "Design Your Own Rounding Word Problem", "type": "interactive", "difficulty": "hard",
             "url": _google_search("how to write a rounding numbers word problem")},
            {"id": "ro-c-2", "title": "Rounding Word Problem Design (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("creating rounding numbers word problems tutorial")},
            {"id": "ro-c-3", "title": "Rounding and Estimation Project Guide", "type": "reading", "difficulty": "hard",
             "url": _google_search("rounding estimation project guide for students")},
        ],
    },
    "parallel-line-angles": {
        "remember": [
            {"id": "pl-r-1", "title": "Parallel Lines and Transversals, Explained", "type": "video", "difficulty": "easy",
             "url": _youtube_search("parallel lines transversal angles explained for beginners")},
            {"id": "pl-r-2", "title": "Parallel Line Angle Rules Cheat Sheet", "type": "reading", "difficulty": "easy",
             "url": _google_search("parallel lines transversal angle rules cheat sheet")},
            {"id": "pl-r-3", "title": "Parallel Line Angles Quiz for Beginners", "type": "quiz", "difficulty": "easy",
             "url": _google_search("parallel lines angles quiz grade 9")},
        ],
        "understand": [
            {"id": "pl-u-1", "title": "Why Corresponding Angles Are Equal", "type": "reading", "difficulty": "easy",
             "url": _google_search("why are corresponding angles equal parallel lines explained")},
            {"id": "pl-u-2", "title": "Alternate and Co-Interior Angles (Video)", "type": "video", "difficulty": "easy",
             "url": _youtube_search("alternate angles co-interior angles explained for beginners")},
            {"id": "pl-u-3", "title": "Try It Yourself: Parallel Line Angles", "type": "interactive", "difficulty": "medium",
             "url": "https://www.mathsisfun.com/geometry/parallel-lines.html"},
        ],
        "apply": [
            {"id": "pl-a-1", "title": "Parallel Line Angles Practice Walkthrough", "type": "video", "difficulty": "medium",
             "url": _youtube_search("parallel lines transversal angles practice walkthrough")},
            {"id": "pl-a-2", "title": "Parallel Line Angles Practice Exercises", "type": "interactive", "difficulty": "medium",
             "url": _google_search("parallel lines angles practice exercises with solutions")},
            {"id": "pl-a-3", "title": "Real-World Parallel Line Angle Examples", "type": "reading", "difficulty": "medium",
             "url": _google_search("parallel lines transversal real world examples architecture")},
        ],
        "analyze": [
            {"id": "pl-n-1", "title": "Corresponding vs Alternate vs Co-Interior", "type": "reading", "difficulty": "hard",
             "url": _google_search("difference between corresponding alternate co-interior angles")},
            {"id": "pl-n-2", "title": "Spotting Angle Relationships in Diagrams (Video)", "type": "video", "difficulty": "medium",
             "url": _youtube_search("identifying angle relationships parallel lines diagram")},
            {"id": "pl-n-3", "title": "Parallel Line Angles Advanced Quiz", "type": "quiz", "difficulty": "hard",
             "url": _google_search("parallel lines angles advanced quiz mixed problems")},
        ],
        "evaluate": [
            {"id": "pl-e-1", "title": "Does One Angle Really Determine All Eight?", "type": "reading", "difficulty": "hard",
             "url": _google_search("one angle determines all angles parallel lines transversal proof")},
            {"id": "pl-e-2", "title": "Parallel Line Angles Critical Thinking (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("parallel lines angles critical thinking tricky questions")},
            {"id": "pl-e-3", "title": "Evaluate Parallel Line Angle Claims", "type": "interactive", "difficulty": "hard",
             "url": _google_search("evaluate true or false parallel line angle claims")},
        ],
        "create": [
            {"id": "pl-c-1", "title": "Design Your Own Parallel Line Angle Problem", "type": "interactive", "difficulty": "hard",
             "url": _google_search("how to write a parallel lines transversal angle problem")},
            {"id": "pl-c-2", "title": "Parallel Line Angle Problem Design (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("creating parallel lines angle word problems tutorial")},
            {"id": "pl-c-3", "title": "Parallel Lines Project Guide", "type": "reading", "difficulty": "hard",
             "url": _google_search("parallel lines angles project guide for students")},
        ],
    },
    "fraction-operations": {
        "remember": [
            {"id": "fc-r-1", "title": "Simplifying Fractions Basics, Explained", "type": "video", "difficulty": "easy",
             "url": _youtube_search("simplifying fractions basics explained for beginners")},
            {"id": "fc-r-2", "title": "Fraction Operations Cheat Sheet", "type": "reading", "difficulty": "easy",
             "url": _google_search("fraction operations cheat sheet simplify add subtract multiply divide")},
            {"id": "fc-r-3", "title": "Fraction Basics Quiz for Beginners", "type": "quiz", "difficulty": "easy",
             "url": _google_search("simplifying fractions quiz grade 9")},
        ],
        "understand": [
            {"id": "fc-u-1", "title": "Why Simplifying Doesn't Change a Fraction's Value", "type": "reading", "difficulty": "easy",
             "url": _google_search("why does simplifying a fraction not change its value explained")},
            {"id": "fc-u-2", "title": "Dividing Fractions: Why We Flip and Multiply (Video)", "type": "video", "difficulty": "easy",
             "url": _youtube_search("why do we flip and multiply when dividing fractions explained")},
            {"id": "fc-u-3", "title": "Try It Yourself: Fraction Simplifier", "type": "interactive", "difficulty": "medium",
             "url": "https://www.mathsisfun.com/simplifying-fractions.html"},
        ],
        "apply": [
            {"id": "fc-a-1", "title": "Fraction Operations Practice Walkthrough", "type": "video", "difficulty": "medium",
             "url": _youtube_search("simplify multiply divide fractions practice walkthrough")},
            {"id": "fc-a-2", "title": "Fraction Operations Practice Exercises", "type": "interactive", "difficulty": "medium",
             "url": _google_search("fraction operations practice exercises with solutions")},
            {"id": "fc-a-3", "title": "Multiplying and Dividing Mixed Numbers", "type": "reading", "difficulty": "medium",
             "url": _google_search("multiplying and dividing mixed numbers explained step by step")},
        ],
        "analyze": [
            {"id": "fc-n-1", "title": "Common Fraction Operation Mistakes", "type": "reading", "difficulty": "hard",
             "url": _google_search("common fraction addition subtraction mistakes explained")},
            {"id": "fc-n-2", "title": "Adding Fractions Word Problems (Video)", "type": "video", "difficulty": "medium",
             "url": _youtube_search("adding subtracting fractions word problems explained")},
            {"id": "fc-n-3", "title": "Fraction Operations Advanced Quiz", "type": "quiz", "difficulty": "hard",
             "url": _google_search("fraction operations advanced quiz mixed problems")},
        ],
        "evaluate": [
            {"id": "fc-e-1", "title": "Comparing Fractions with Different Denominators", "type": "reading", "difficulty": "hard",
             "url": _google_search("how to compare fractions with different denominators explained")},
            {"id": "fc-e-2", "title": "Fraction Comparison Critical Thinking (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("comparing fractions critical thinking tricky questions")},
            {"id": "fc-e-3", "title": "Evaluate Fraction Comparison Claims", "type": "interactive", "difficulty": "hard",
             "url": _google_search("evaluate true or false fraction comparison claims")},
        ],
        "create": [
            {"id": "fc-c-1", "title": "Design Your Own Fraction Word Problem", "type": "interactive", "difficulty": "hard",
             "url": _google_search("how to write a fraction operations word problem")},
            {"id": "fc-c-2", "title": "Fraction Word Problem Design (Video)", "type": "video", "difficulty": "hard",
             "url": _youtube_search("creating fraction word problems tutorial")},
            {"id": "fc-c-3", "title": "Fraction Operations Project Guide", "type": "reading", "difficulty": "hard",
             "url": _google_search("fraction operations project guide for students")},
        ],
    },
}


def get_lesson_resources(lesson_id: str, lo_name: str) -> list[dict]:
    return LESSON_RESOURCES.get(lesson_id, {}).get(lo_name, [])
