/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackFieldAnalyticsRouteImport } from './routes/track-field-analytics'
import { Route as TimeGuardiansRoundingClockRouteImport } from './routes/time-guardians-rounding-clock'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PirateNavigatorRouteImport } from './routes/pirate-navigator'
import { Route as PatternIslandsRouteImport } from './routes/pattern-islands'
import { Route as MagiciansTriangleHouseRouteImport } from './routes/magicians-triangle-house'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as LaserHeistParallelMuseumRouteImport } from './routes/laser-heist-parallel-museum'
import { Route as FractionRoomRouteImport } from './routes/fraction-room'
import { Route as FractionChefRecipeRescueRouteImport } from './routes/fraction-chef-recipe-rescue'
import { Route as FishTankShopRouteImport } from './routes/fish-tank-shop'
import { Route as EquationsEcoRouteImport } from './routes/equations-eco'
import { Route as EcoBloomsLandSaleRouteImport } from './routes/eco-blooms-land-sale'
import { Route as DarkRoomEscapeRouteImport } from './routes/dark-room-escape'
import { Route as AlchemistsPotionLabRouteImport } from './routes/alchemists-potion-lab'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdaptiveRouteImport } from './routes/adaptive'
import { Route as IndexRouteImport } from './routes/index'

const TrackFieldAnalyticsRoute = TrackFieldAnalyticsRouteImport.update({
  id: '/track-field-analytics',
  path: '/track-field-analytics',
  getParentRoute: () => rootRouteImport,
})
const TimeGuardiansRoundingClockRoute =
  TimeGuardiansRoundingClockRouteImport.update({
    id: '/time-guardians-rounding-clock',
    path: '/time-guardians-rounding-clock',
    getParentRoute: () => rootRouteImport,
  })
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
})
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
})
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
})
const PirateNavigatorRoute = PirateNavigatorRouteImport.update({
  id: '/pirate-navigator',
  path: '/pirate-navigator',
  getParentRoute: () => rootRouteImport,
})
const PatternIslandsRoute = PatternIslandsRouteImport.update({
  id: '/pattern-islands',
  path: '/pattern-islands',
  getParentRoute: () => rootRouteImport,
})
const MagiciansTriangleHouseRoute = MagiciansTriangleHouseRouteImport.update({
  id: '/magicians-triangle-house',
  path: '/magicians-triangle-house',
  getParentRoute: () => rootRouteImport,
})
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
})
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
})
const LaserHeistParallelMuseumRoute =
  LaserHeistParallelMuseumRouteImport.update({
    id: '/laser-heist-parallel-museum',
    path: '/laser-heist-parallel-museum',
    getParentRoute: () => rootRouteImport,
  })
const FractionRoomRoute = FractionRoomRouteImport.update({
  id: '/fraction-room',
  path: '/fraction-room',
  getParentRoute: () => rootRouteImport,
})
const FractionChefRecipeRescueRoute =
  FractionChefRecipeRescueRouteImport.update({
    id: '/fraction-chef-recipe-rescue',
    path: '/fraction-chef-recipe-rescue',
    getParentRoute: () => rootRouteImport,
  })
const FishTankShopRoute = FishTankShopRouteImport.update({
  id: '/fish-tank-shop',
  path: '/fish-tank-shop',
  getParentRoute: () => rootRouteImport,
})
const EquationsEcoRoute = EquationsEcoRouteImport.update({
  id: '/equations-eco',
  path: '/equations-eco',
  getParentRoute: () => rootRouteImport,
})
const EcoBloomsLandSaleRoute = EcoBloomsLandSaleRouteImport.update({
  id: '/eco-blooms-land-sale',
  path: '/eco-blooms-land-sale',
  getParentRoute: () => rootRouteImport,
})
const DarkRoomEscapeRoute = DarkRoomEscapeRouteImport.update({
  id: '/dark-room-escape',
  path: '/dark-room-escape',
  getParentRoute: () => rootRouteImport,
})
const AlchemistsPotionLabRoute = AlchemistsPotionLabRouteImport.update({
  id: '/alchemists-potion-lab',
  path: '/alchemists-potion-lab',
  getParentRoute: () => rootRouteImport,
})
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
})
const AdaptiveRoute = AdaptiveRouteImport.update({
  id: '/adaptive',
  path: '/adaptive',
  getParentRoute: () => rootRouteImport,
})
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AdaptiveRoute: AdaptiveRoute,
  AdminRoute: AdminRoute,
  AlchemistsPotionLabRoute: AlchemistsPotionLabRoute,
  DarkRoomEscapeRoute: DarkRoomEscapeRoute,
  EcoBloomsLandSaleRoute: EcoBloomsLandSaleRoute,
  EquationsEcoRoute: EquationsEcoRoute,
  FishTankShopRoute: FishTankShopRoute,
  FractionChefRecipeRescueRoute: FractionChefRecipeRescueRoute,
  FractionRoomRoute: FractionRoomRoute,
  LaserHeistParallelMuseumRoute: LaserHeistParallelMuseumRoute,
  LessonsRoute: LessonsRoute,
  LoginRoute: LoginRoute,
  MagiciansTriangleHouseRoute: MagiciansTriangleHouseRoute,
  PatternIslandsRoute: PatternIslandsRoute,
  PirateNavigatorRoute: PirateNavigatorRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  TeacherRoute: TeacherRoute,
  TimeGuardiansRoundingClockRoute: TimeGuardiansRoundingClockRoute,
  TrackFieldAnalyticsRoute: TrackFieldAnalyticsRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
